import { useCallback, useEffect, useRef, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, Maximize2, Moon, Pause, Play, Repeat2, Sun, X } from 'lucide-react'
import { Button, StatusBadge } from '../../components/ui'
import type { IdeaRecord } from '../research/research-api'
import { loadShootingBrief, markShootingPackSegment } from './pilot-api'
import type { ShootingFormat, ShootingPackSegment } from './pilot-api'
import { useI18n } from '../i18n/i18n'
import { SkitBossSegment } from './SkitBossSegment'

type Mode='compact'|'script'|'teleprompter'
type WakeLockLike={release:()=>Promise<void>;addEventListener:(type:'release',listener:()=>void)=>void}
type WakeNavigator=Navigator&{wakeLock?:{request:(type:'screen')=>Promise<WakeLockLike>}}

export function BossMode({idea,onClose}:{idea:IdeaRecord;onClose:()=>void}){
 const{language}=useI18n();const zh=language==='zh-CN';const[format,setFormat]=useState<ShootingFormat>('q_and_a');const[segments,setSegments]=useState<ShootingPackSegment[]>([]);const[index,setIndex]=useState(0);const[mode,setModeState]=useState<Mode>('compact');const[dark,setDark]=useState(true);const[font,setFont]=useState(46);const[lineHeight,setLineHeight]=useState(1.55);const[speed,setSpeed]=useState(34);const[playing,setPlaying]=useState(false);const[countdown,setCountdown]=useState<number|null>(null);const[mirror,setMirror]=useState(false);const[busy,setBusy]=useState(false);const scrollRef=useRef<HTMLDivElement>(null);const touchRef=useRef<number|null>(null);const wakeLockRef=useRef<WakeLockLike|null>(null)
 useEffect(()=>{void loadShootingBrief(idea.id).then(brief=>{setFormat(brief?.shooting_format??'q_and_a');setSegments(brief?.pack_segments??[])})},[idea.id])
 const releaseWakeLock=useCallback(async()=>{const lock=wakeLockRef.current;wakeLockRef.current=null;if(lock)await lock.release().catch(()=>undefined)},[])
 const requestWakeLock=useCallback(async()=>{const wake=(navigator as WakeNavigator).wakeLock;if(!wake)return;try{const lock=await wake.request('screen');wakeLockRef.current=lock;lock.addEventListener('release',()=>{if(wakeLockRef.current===lock)wakeLockRef.current=null})}catch{/* Wake Lock is optional and may be denied by the browser. */}},[])
 const stop=useCallback(()=>{setPlaying(false);setCountdown(null);void releaseWakeLock()},[releaseWakeLock])
 useEffect(()=>()=>{void releaseWakeLock()},[releaseWakeLock])
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='ArrowLeft'){stop();setIndex(value=>Math.max(0,value-1))}if(event.key==='ArrowRight'){stop();setIndex(value=>Math.min(segments.length-1,value+1))}if(event.key==='Escape'){void releaseWakeLock();onClose()}if(event.key===' '&&mode==='teleprompter'){event.preventDefault();if(playing||countdown!==null)stop();else setCountdown(3)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[countdown,mode,onClose,playing,releaseWakeLock,segments.length,stop])
 useEffect(()=>{if(countdown===null)return;if(countdown>1){const timer=window.setTimeout(()=>setCountdown(value=>value===null?null:value-1),1000);return()=>window.clearTimeout(timer)}const timer=window.setTimeout(()=>{setCountdown(null);setPlaying(true)},1000);return()=>window.clearTimeout(timer)},[countdown])
 useEffect(()=>{if(!playing||mode!=='teleprompter')return;let frame=0;let previous=performance.now();const tick=(now:number)=>{const container=scrollRef.current;if(container){const max=container.scrollHeight-container.clientHeight;const next=container.scrollTop+(now-previous)*speed/1000;container.scrollTop=Math.min(next,max);if(next>=max-1){setPlaying(false);void releaseWakeLock();return}}previous=now;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[mode,playing,releaseWakeLock,speed])
 useEffect(()=>{if(scrollRef.current)scrollRef.current.scrollTop=0},[index,mode])
 const current=segments[index];const full=()=>document.fullscreenElement?void document.exitFullscreen():void document.documentElement.requestFullscreen()
 const toggle=async()=>{if(!current)return;setBusy(true);try{await markShootingPackSegment(idea.id,current.id,!current.isShot);setSegments(rows=>rows.map(item=>item.id===current.id?{...item,isShot:!item.isShot}:item))}finally{setBusy(false)}}
 const go=(delta:number)=>{stop();setIndex(value=>Math.max(0,Math.min(segments.length-1,value+delta)))}
 const setMode=(next:Mode)=>{stop();setModeState(next)}
 const start=async()=>{if(playing||countdown!==null){stop();return}if(scrollRef.current&&scrollRef.current.scrollTop>=scrollRef.current.scrollHeight-scrollRef.current.clientHeight-2)scrollRef.current.scrollTop=0;await requestWakeLock();setCountdown(3)}
 const close=()=>{void releaseWakeLock();onClose()}
 return <div data-testid="boss-mode" className={`fixed inset-0 z-[100] flex h-dvh flex-col overflow-hidden ${dark?'bg-[#07151c] text-white':'bg-[#fffdf8] text-ink'}`} onTouchStart={event=>touchRef.current=event.touches[0].clientX} onTouchEnd={event=>{if(touchRef.current===null)return;const delta=event.changedTouches[0].clientX-touchRef.current;if(delta>60)go(-1);if(delta<-60)go(1);touchRef.current=null}}>
  <header className="z-20 shrink-0 border-b border-current/10 bg-inherit px-2 py-2 sm:px-6 sm:py-3"><div className="flex items-center justify-between gap-2"><p className="min-w-0 truncate text-xs font-bold opacity-60">{idea.title}</p><div className="flex shrink-0 items-center gap-1"><Button size="icon" variant="ghost" onClick={()=>setDark(value=>!value)}>{dark?<Sun className="size-4"/>:<Moon className="size-4"/>}</Button><Button size="icon" variant="ghost" onClick={full}><Maximize2 className="size-4"/></Button><Button size="icon" variant="ghost" onClick={close}><X className="size-4"/></Button></div></div><div className="mt-1 grid grid-cols-3 gap-1 sm:mx-auto sm:max-w-md"><Button size="sm" variant={mode==='compact'?'primary':'ghost'} onClick={()=>setMode('compact')}>{zh?'简洁':'Compact'}</Button><Button size="sm" variant={mode==='script'?'primary':'ghost'} onClick={()=>setMode('script')}>{zh?'台词':'Script'}</Button><Button size="sm" variant={mode==='teleprompter'?'primary':'ghost'} onClick={()=>setMode('teleprompter')}>{zh?'提词器':'Teleprompter'}</Button></div></header>
  {mode!=='teleprompter'?<main className="min-h-0 flex-1 overflow-y-auto px-4 py-4 sm:flex sm:flex-col sm:items-center sm:justify-center sm:px-8 sm:py-8 sm:text-center"><div className="flex items-center gap-3"><p className="text-xs font-bold uppercase tracking-[.16em] opacity-45">{Math.min(index+1,segments.length||1)} / {segments.length||1}</p>{current?.isShot?<StatusBadge tone="success">✓ {zh?'已拍':'Shot'}</StatusBadge>:null}</div><h1 className="mt-3 max-w-6xl font-display text-2xl font-semibold leading-snug sm:mt-7 sm:text-5xl">{current?.prompt||idea.title}</h1>{format==='skit'&&current?<SkitBossSegment segment={current} zh={zh}/>:null}{mode==='script'&&format!=='skit'&&current?.referenceScript?<blockquote className="mt-4 max-w-5xl rounded-xl border border-coral/25 bg-coral/10 p-4 text-left sm:mt-7 sm:p-7"><p className="text-xs font-extrabold tracking-[.16em] text-coral-light">🎤 {zh?'参考台词':'Reference Script'}</p><p className="mt-3 whitespace-pre-wrap text-[1.08rem] leading-7 sm:text-2xl sm:leading-[1.65]">{current.referenceScript}</p></blockquote>:null}{current?.keywords.length?<div className="mt-4 max-w-4xl sm:mt-7"><p className="text-xs font-extrabold tracking-[.16em] text-coral-light">💡 {zh?'表达重点':'Keywords'}</p><p className="mt-2 text-lg leading-7 opacity-75 sm:text-2xl sm:leading-9">{current.keywords.join(' · ')}</p></div>:null}</main>:<main className="relative min-h-0 flex-1 overflow-hidden"><div ref={scrollRef} className="h-full overflow-y-auto overscroll-contain px-5 sm:px-10"><div className="mx-auto max-w-6xl pb-[72vh] pt-[10vh]" style={{transform:mirror?'scaleX(-1)':'none'}}><p className="mb-8 text-center text-lg opacity-45 sm:mb-12 sm:text-xl">{current?.prompt}</p><div className="whitespace-pre-wrap font-semibold" style={{fontSize:font,lineHeight}}>{format==='skit'?(current?.dialogues??[]).map(item=>item.character+'：'+item.line).join('\\n\\n')||current?.rawText||current?.prompt||idea.title:current?.referenceScript||current?.prompt||idea.title}</div></div></div>{countdown!==null?<div className="absolute inset-0 grid place-items-center bg-black/55"><span className="font-display text-[30vw] font-bold text-white sm:text-[12rem]">{countdown}</span></div>:null}</main>}
  <footer className="z-20 shrink-0 border-t border-current/10 bg-inherit px-2 py-2"><div className="flex items-center justify-center gap-1.5"><Button size="sm" variant="secondary" disabled={index===0} onClick={()=>go(-1)}><ChevronLeft className="size-4"/><span className="hidden sm:inline">{zh?'上一段':'Previous'}</span></Button><Button size="sm" variant={current?.isShot?'secondary':'ghost'} disabled={!current||busy} onClick={()=>void toggle()}><Check className="size-4"/>{current?.isShot?(zh?'已拍':'Shot'):(zh?'标记已拍':'Mark Shot')}</Button>{mode==='teleprompter'?<Button size="sm" onClick={()=>void start()}>{playing||countdown!==null?<Pause className="size-4"/>:<Play className="size-4"/>}{playing?(zh?'暂停':'Pause'):countdown!==null?(zh?'取消':'Cancel'):(zh?'开始':'Start')}</Button>:null}<Button size="sm" disabled={index>=segments.length-1} onClick={()=>go(1)}><span className="hidden sm:inline">{zh?'下一段':'Next'}</span><ChevronRight className="size-4"/></Button></div>{mode==='teleprompter'?<div className="mx-auto mt-2 grid max-w-3xl grid-cols-2 gap-x-3 gap-y-1 text-[.65rem] font-bold sm:grid-cols-4"><label>{zh?'速度':'Speed'} <input className="w-full" type="range" min="8" max="100" value={speed} onChange={event=>setSpeed(Number(event.target.value))}/></label><label>{zh?'字号':'Font'} <input className="w-full" type="range" min="30" max="88" value={font} onChange={event=>setFont(Number(event.target.value))}/></label><label>{zh?'行距':'Line height'} <input className="w-full" type="range" min="1.2" max="2" step="0.05" value={lineHeight} onChange={event=>setLineHeight(Number(event.target.value))}/></label><Button size="sm" variant={mirror?'primary':'ghost'} onClick={()=>setMirror(value=>!value)}><Repeat2 className="size-3.5"/>{zh?'镜像':'Mirror'}</Button></div>:null}</footer>
 </div>
}