import { useEffect, useRef, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, Maximize2, Moon, Pause, Play, Repeat2, Sun, X } from 'lucide-react'
import { Button, StatusBadge } from '../../components/ui'
import type { IdeaRecord } from '../research/research-api'
import { loadShootingBrief, markShootingPackSegment } from './pilot-api'
import type { ShootingPackSegment } from './pilot-api'
import { useI18n } from '../i18n/i18n'

type Mode='compact'|'script'|'teleprompter'
export function BossMode({idea,onClose}:{idea:IdeaRecord;onClose:()=>void}){
 const{language}=useI18n();const zh=language==='zh-CN';const[segments,setSegments]=useState<ShootingPackSegment[]>([]);const[index,setIndex]=useState(0);const[mode,setMode]=useState<Mode>('compact');const[dark,setDark]=useState(true);const[font,setFont]=useState(46);const[speed,setSpeed]=useState(34);const[playing,setPlaying]=useState(false);const[mirror,setMirror]=useState(false);const[busy,setBusy]=useState(false);const scrollRef=useRef<HTMLDivElement>(null);const touchRef=useRef<number|null>(null)
 useEffect(()=>{void loadShootingBrief(idea.id).then(brief=>setSegments(brief?.pack_segments??[]))},[idea.id])
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='ArrowLeft')setIndex(value=>Math.max(0,value-1));if(event.key==='ArrowRight')setIndex(value=>Math.min(segments.length-1,value+1));if(event.key==='Escape')onClose();if(event.key===' ')setPlaying(value=>!value)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[onClose,segments.length])
 useEffect(()=>{if(!playing||mode!=='teleprompter')return;let frame=0;let previous=performance.now();const tick=(now:number)=>{if(scrollRef.current)scrollRef.current.scrollTop+=(now-previous)*speed/1000;previous=now;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[mode,playing,speed])
 useEffect(()=>{if(scrollRef.current)scrollRef.current.scrollTop=0},[index,mode])
 const current=segments[index];const full=()=>document.fullscreenElement?void document.exitFullscreen():void document.documentElement.requestFullscreen()
 const toggle=async()=>{if(!current)return;setBusy(true);try{await markShootingPackSegment(idea.id,current.id,!current.isShot);setSegments(rows=>rows.map(item=>item.id===current.id?{...item,isShot:!item.isShot}:item))}finally{setBusy(false)}}
 const go=(delta:number)=>{setPlaying(false);setIndex(value=>Math.max(0,Math.min(segments.length-1,value+delta)))}
 return <div data-testid="boss-mode" className={`fixed inset-0 z-[100] flex flex-col ${dark?'bg-[#07151c] text-white':'bg-[#fffdf8] text-ink'}`} onTouchStart={event=>touchRef.current=event.touches[0].clientX} onTouchEnd={event=>{if(touchRef.current===null)return;const delta=event.changedTouches[0].clientX-touchRef.current;if(delta>60)go(-1);if(delta<-60)go(1);touchRef.current=null}}>
  <header className="flex flex-wrap items-center justify-between gap-2 border-b border-current/10 px-4 py-3 sm:px-6"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-coral-light">{zh?'Steven 拍摄模式':'Steven Shooting Mode'}</p><p className="mt-1 max-w-[44vw] truncate text-sm opacity-65">{idea.title}</p></div><div className="flex flex-wrap items-center gap-1"><Button size="sm" variant={mode==='compact'?'primary':'ghost'} onClick={()=>setMode('compact')}>{zh?'简洁':'Compact'}</Button><Button size="sm" variant={mode==='script'?'primary':'ghost'} onClick={()=>setMode('script')}>{zh?'台词':'Script'}</Button><Button size="sm" variant={mode==='teleprompter'?'primary':'ghost'} onClick={()=>setMode('teleprompter')}>{zh?'提词器':'Teleprompter'}</Button><Button size="icon" variant="ghost" onClick={()=>setDark(value=>!value)}>{dark?<Sun className="size-5"/>:<Moon className="size-5"/>}</Button><Button size="icon" variant="ghost" onClick={full}><Maximize2 className="size-5"/></Button><Button size="icon" variant="ghost" onClick={onClose}><X className="size-5"/></Button></div></header>
  {mode!=='teleprompter'?<main className="flex min-h-0 flex-1 flex-col items-center justify-center overflow-y-auto px-5 py-8 text-center"><div className="flex items-center gap-3"><p className="text-sm font-bold uppercase tracking-[.2em] opacity-50">{zh?'段落':'Segment'} {Math.min(index+1,segments.length||1)} / {segments.length||1}</p>{current?.isShot?<StatusBadge tone="success">✓ {zh?'已拍':'Shot'}</StatusBadge>:null}</div><h1 className="mt-7 max-w-6xl font-display font-semibold leading-[1.2]" style={{fontSize:`clamp(2rem,6vw,${font}px)`}}>{current?.prompt||idea.title}</h1>{mode==='script'&&current?.referenceScript?<blockquote className="mt-9 max-w-5xl rounded-2xl border border-coral/25 bg-coral/10 px-7 py-6 text-left"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-coral-light">🎤 {zh?'参考台词':'Reference Script'}</p><p className="mt-4 whitespace-pre-wrap text-2xl leading-[1.65] opacity-90">{current.referenceScript}</p></blockquote>:null}{current?.keywords.length?<div className="mt-9 max-w-4xl"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-coral-light">💡 {zh?'表达重点 / Keywords':'Keywords'}</p><p className="mt-3 text-2xl leading-9 opacity-75">{current.keywords.join(' · ')}</p></div>:null}</main>:<main className="min-h-0 flex-1 overflow-hidden px-4 py-5 sm:px-10"><div ref={scrollRef} className="mx-auto h-full max-w-6xl overflow-y-auto px-4 py-[35vh]" style={{transform:mirror?'scaleX(-1)':'none'}}><p className="mb-12 text-center text-xl opacity-45">{current?.prompt}</p><div className="whitespace-pre-wrap font-semibold" style={{fontSize:font,lineHeight:1.55}}>{current?.referenceScript||current?.prompt||idea.title}</div></div></main>}
  <footer className="flex flex-wrap items-center justify-center gap-2 border-t border-current/10 px-4 py-3"><Button variant="secondary" disabled={index===0} onClick={()=>go(-1)}><ChevronLeft className="size-5"/>{zh?'上一段':'Previous'}</Button><Button variant={current?.isShot?'secondary':'ghost'} disabled={!current||busy} onClick={()=>void toggle()}><Check className="size-5"/>{current?.isShot?(zh?'已拍':'Shot'):(zh?'标记已拍':'Mark Shot')}</Button>{mode==='teleprompter'?<><Button onClick={()=>setPlaying(value=>!value)}>{playing?<Pause className="size-5"/>:<Play className="size-5"/>}{playing?(zh?'暂停':'Pause'):(zh?'继续':'Continue')}</Button><label className="text-xs font-bold">{zh?'速度':'Speed'} <input type="range" min="8" max="100" value={speed} onChange={event=>setSpeed(Number(event.target.value))}/></label><Button variant={mirror?'primary':'ghost'} onClick={()=>setMirror(value=>!value)}><Repeat2 className="size-4"/>{zh?'镜像':'Mirror'}</Button></>:null}<label className="text-xs font-bold">{zh?'字号':'Font'} <input type="range" min="30" max="88" value={font} onChange={event=>setFont(Number(event.target.value))}/></label><Button disabled={index>=segments.length-1} onClick={()=>go(1)}>{zh?'下一段':'Next'}<ChevronRight className="size-5"/></Button></footer>
 </div>
}