import { useEffect, useRef, useState } from 'react'
import { ChevronLeft, ChevronRight, Maximize2, Minimize2, Moon, Pause, Play, Repeat2, Sun, X } from 'lucide-react'
import { Button } from '../../components/ui'
import type { IdeaRecord } from '../research/research-api'
import { loadShootingBrief } from './pilot-api'
import { useI18n } from '../i18n/i18n'

export function BossMode({idea,onClose}:{idea:IdeaRecord;onClose:()=>void}){
  const{language}=useI18n();const zh=language==='zh-CN';const[questions,setQuestions]=useState<string[]>([]);const[points,setPoints]=useState<string[]>([]);const[cta,setCta]=useState('');const[index,setIndex]=useState(0);const[mode,setMode]=useState<'qa'|'teleprompter'>('qa');const[dark,setDark]=useState(true);const[font,setFont]=useState(44);const[speed,setSpeed]=useState(32);const[lineHeight,setLineHeight]=useState(1.55);const[playing,setPlaying]=useState(false);const[mirror,setMirror]=useState(false);const scrollRef=useRef<HTMLDivElement>(null);const touchRef=useRef<number|null>(null)
  useEffect(()=>{void loadShootingBrief(idea.id).then(b=>{if(!b)return;setQuestions(b.interview_questions);setPoints(b.key_talking_points);setCta(b.suggested_cta??'')})},[idea.id])
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')setIndex(v=>Math.max(0,v-1));if(e.key==='ArrowRight')setIndex(v=>Math.min(questions.length-1,v+1));if(e.key==='Escape')onClose()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[onClose,questions.length])
  useEffect(()=>{if(!playing||mode!=='teleprompter')return;let frame=0;let previous=performance.now();const tick=(now:number)=>{if(scrollRef.current)scrollRef.current.scrollTop+=(now-previous)*speed/1000;previous=now;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[mode,playing,speed])
  const full=()=>document.fullscreenElement?void document.exitFullscreen():void document.documentElement.requestFullscreen()
  const script=[idea.original_hook,idea.our_angle,cta].filter(Boolean).join('\n\n')
  return <div data-testid="boss-mode" className={`fixed inset-0 z-[100] flex flex-col ${dark?'bg-[#07151c] text-white':'bg-[#fffdf8] text-ink'}`} onTouchStart={e=>touchRef.current=e.touches[0].clientX} onTouchEnd={e=>{if(touchRef.current===null)return;const delta=e.changedTouches[0].clientX-touchRef.current;if(delta>60)setIndex(v=>Math.max(0,v-1));if(delta<-60)setIndex(v=>Math.min(questions.length-1,v+1));touchRef.current=null}}>
    <header className="flex flex-wrap items-center justify-between gap-2 border-b border-current/10 px-4 py-3 sm:px-6"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-coral-light">{zh?'老板模式 / 拍摄模式':'Boss / Shooting Mode'}</p><p className="mt-1 max-w-[50vw] truncate text-sm opacity-65">{idea.title}</p></div><div className="flex flex-wrap items-center gap-1"><Button size="sm" variant={mode==='qa'?'primary':'ghost'} onClick={()=>setMode('qa')}>Q&A</Button><Button size="sm" variant={mode==='teleprompter'?'primary':'ghost'} onClick={()=>setMode('teleprompter')}>{zh?'提词器':'Teleprompter'}</Button><Button size="icon" variant="ghost" onClick={()=>setDark(v=>!v)}>{dark?<Sun className="size-5"/>:<Moon className="size-5"/>}</Button><Button size="icon" variant="ghost" onClick={full}>{document.fullscreenElement?<Minimize2 className="size-5"/>:<Maximize2 className="size-5"/>}</Button><Button size="icon" variant="ghost" onClick={onClose}><X className="size-5"/></Button></div></header>
    {mode==='qa'?<main className="flex flex-1 flex-col items-center justify-center overflow-y-auto px-5 py-8 text-center"><p className="text-sm font-bold uppercase tracking-[.2em] opacity-50">{zh?'问题':'Question'} {Math.min(index+1,questions.length||1)} / {questions.length||1}</p><h1 className="mt-7 max-w-5xl font-display font-semibold leading-[1.2]" style={{fontSize:`clamp(2rem,6vw,${font}px)`}}>{questions[index]||idea.original_hook||idea.title}</h1>{points.length?<div className="mt-10 max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-coral-light">{zh?'表达方向 / 关键词':'Talking Points / Keywords'}</p><p className="mt-3 text-xl leading-8 opacity-75">{points[Math.min(index,points.length-1)]}</p></div>:null}</main>:<main className="min-h-0 flex-1 overflow-hidden px-4 py-5 sm:px-10"><div ref={scrollRef} className="mx-auto h-full max-w-5xl overflow-y-auto px-4 py-[35vh]" style={{transform:mirror?'scaleX(-1)':'none'}}><div className="whitespace-pre-wrap font-semibold" style={{fontSize:font,lineHeight}}>{script||idea.title}</div></div></main>}
    <footer className="flex flex-wrap items-center justify-center gap-2 border-t border-current/10 px-4 py-3">{mode==='qa'?<><Button variant="secondary" disabled={index===0} onClick={()=>setIndex(v=>Math.max(0,v-1))}><ChevronLeft className="size-5"/>{zh?'上一题':'Previous'}</Button><input aria-label="Font size" type="range" min="30" max="72" value={font} onChange={e=>setFont(Number(e.target.value))}/><Button disabled={index>=questions.length-1} onClick={()=>setIndex(v=>Math.min(questions.length-1,v+1))}>{zh?'下一题':'Next'}<ChevronRight className="size-5"/></Button></>:<><Button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause className="size-5"/>:<Play className="size-5"/>}{playing?(zh?'暂停':'Pause'):(zh?'开始':'Start')}</Button><label className="text-xs font-bold">{zh?'速度':'Speed'} <input type="range" min="8" max="100" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label><label className="text-xs font-bold">{zh?'字号':'Font'} <input type="range" min="28" max="80" value={font} onChange={e=>setFont(Number(e.target.value))}/></label><label className="text-xs font-bold">{zh?'行距':'Line height'} <input type="range" min="12" max="24" value={lineHeight*10} onChange={e=>setLineHeight(Number(e.target.value)/10)}/></label><Button variant={mirror?'primary':'ghost'} onClick={()=>setMirror(v=>!v)}><Repeat2 className="size-4"/>{zh?'镜像':'Mirror'}</Button></>}</footer>
  </div>
}
