import{useEffect,useState}from'react'
import{Camera,LoaderCircle,Save}from'lucide-react'
import{Button,Card,FormField,Input,Select,Textarea}from'../../components/ui'
import{loadContributorOptions}from'../research/research-api'
import type{IdeaRecord,ReferenceRecord}from'../research/research-api'
import{loadShootingBrief,saveShootingBrief}from'./pilot-api'
const lines=(value:string)=>value.split('\n').map((item)=>item.trim()).filter(Boolean)
export function ShootingBrief({idea,references}:{idea:IdeaRecord;references:ReferenceRecord[]}){const[brief,setBrief]=useState({why_now:'',questions:'',points:'',cta:'',duration:'',talent:'',shootDate:'',location:'',shooter:''});const[people,setPeople]=useState<Array<{user_profile_id:string;display_name:string}>>([]);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('')
useEffect(()=>{void Promise.all([loadShootingBrief(idea.id),loadContributorOptions(idea.client_id)]).then(([saved,options])=>{setPeople(options);if(saved)setBrief({why_now:saved.why_now??'',questions:saved.interview_questions.join('\n'),points:saved.key_talking_points.join('\n'),cta:saved.suggested_cta??'',duration:saved.target_duration??'',talent:saved.talent??'',shootDate:saved.shoot_date??'',location:saved.location??'',shooter:saved.shooter_user_id??''})})},[idea.client_id,idea.id])
async function save(){setBusy(true);try{await saveShootingBrief(idea.id,{why_now:brief.why_now,interview_questions:lines(brief.questions).slice(0,5),key_talking_points:lines(brief.points),suggested_cta:brief.cta,target_duration:brief.duration,talent:brief.talent,shoot_date:brief.shootDate||null,location:brief.location,shooter_user_id:brief.shooter||null});setNotice('拍摄简报已保存 / Shooting brief saved')}finally{setBusy(false)}}
return <div className="space-y-5"><Card className="border-coral/25 bg-coral/[.035]"><div className="flex gap-3"><Camera className="mt-1 size-5 text-coral"/><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-coral">拍摄简报 / Shooting Brief</p><h3 className="mt-2 text-2xl font-bold">{idea.title}</h3><p className="mt-2 text-sm text-ink-muted">给出可直接用于访问与拍摄的表达方向，不替出镜者决定固定立场。</p></div></div></Card>{notice?<p className="rounded-lg bg-green/8 p-3 text-sm text-green">{notice}</p>:null}<div className="grid gap-5 lg:grid-cols-2"><FormField label="Why Now / 为什么现在值得讲"><Textarea value={brief.why_now} onChange={e=>setBrief({...brief,why_now:e.target.value})}/></FormField><FormField label="Suggested Hook / 建议开场"><Textarea value={idea.original_hook??''} readOnly/></FormField><FormField label="Interview Questions / 访问提问" hint="每行一题，最多 5 题"><Textarea rows={7} value={brief.questions} onChange={e=>setBrief({...brief,questions:e.target.value})}/></FormField><FormField label="Key Talking Points / 核心表达方向" hint="每行一个方向，不是标准答案"><Textarea rows={7} value={brief.points} onChange={e=>setBrief({...brief,points:e.target.value})}/></FormField><FormField label="Suggested CTA"><Input value={brief.cta} onChange={e=>setBrief({...brief,cta:e.target.value})}/></FormField><FormField label="Format"><Input value={idea.suggested_format??''} readOnly/></FormField><FormField label="Target Duration"><Input value={brief.duration} onChange={e=>setBrief({...brief,duration:e.target.value})}/></FormField><FormField label="Talent / 出镜"><Input value={brief.talent} onChange={e=>setBrief({...brief,talent:e.target.value})}/></FormField><FormField label="Shoot Date"><Input type="date" value={brief.shootDate} onChange={e=>setBrief({...brief,shootDate:e.target.value})}/></FormField><FormField label="Location"><Input value={brief.location} onChange={e=>setBrief({...brief,location:e.target.value})}/></FormField><FormField label="Shooter / 拍摄"><Select value={brief.shooter} onChange={e=>setBrief({...brief,shooter:e.target.value})}><option value="">Unassigned</option>{people.map(person=><option key={person.user_profile_id} value={person.user_profile_id}>{person.display_name}</option>)}</Select></FormField><div><p className="text-sm font-bold">References</p><div className="mt-2 space-y-2">{references.filter(r=>idea.referenceIds.includes(r.id)).map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer" className="block truncate rounded-lg border border-line p-3 text-sm text-blue">{r.title}</a>)}</div></div></div><Button onClick={()=>void save()} disabled={busy}>{busy?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}保存拍摄简报</Button><details className="rounded-xl border border-line"><summary className="cursor-pointer px-4 py-3 font-bold">更多 / Internal Notes</summary><div className="border-t border-line p-4 text-sm text-ink-muted"><p>{idea.notes||'No internal notes.'}</p></div></details></div>}
