import { useCallback, useEffect, useState } from 'react'
import { BookOpen, LoaderCircle } from 'lucide-react'
import { Button, Card, FormField, Select, StatusBadge } from '../../components/ui'
import { assignContentEditingPreset, loadContentPresetSnapshots, loadEditingPresets } from '../brand/editing-presets-api'
import type { ContentPresetSnapshot, EditingPreset } from '../brand/editing-presets-api'
import { useI18n } from '../i18n/i18n'

const slots=['subtitle','opening','info_insert','other'] as const
const slotText={subtitle:['字幕规范','Subtitle'],opening:['开场规范','Opening'],info_insert:['资讯插入','Info insert'],other:['其他制作规范','Other standard']} as const
export function ContentPresetPanel({contentId,clientId,canManage}:{contentId:string;clientId:string;canManage:boolean}){
 const{language}=useI18n();const zh=language==='zh-CN';const[items,setItems]=useState<EditingPreset[]>([]);const[snapshots,setSnapshots]=useState<ContentPresetSnapshot[]>([]);const[slot,setSlot]=useState<(typeof slots)[number]>('subtitle');const[preset,setPreset]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('')
 const refresh=useCallback(async()=>{const[a,b]=await Promise.all([loadEditingPresets(clientId),loadContentPresetSnapshots(contentId)]);setItems(a.filter(i=>i.status==='active'));setSnapshots(b);setPreset(current=>current||a.find(i=>i.status==='active')?.id||'')},[clientId,contentId])
 useEffect(()=>{const timer=window.setTimeout(()=>void refresh().catch(e=>setError(e instanceof Error?e.message:'Unable to load presets')),0);return()=>window.clearTimeout(timer)},[refresh])
 async function assign(){if(!preset)return;setBusy(true);try{await assignContentEditingPreset(contentId,preset,slot);await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to assign preset')}finally{setBusy(false)}}
 return <Card><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><BookOpen className="size-5 text-blue"/><h3 className="text-lg font-bold">{zh?'本内容制作规范':'Content Production Presets'}</h3></div><StatusBadge tone="info">{zh?'版本快照':'Version snapshot'}</StatusBadge></div><p className="mt-2 text-sm text-ink-muted">{zh?'选择后保存当时版本；以后修改规范不会改写本内容历史':'The selected version is frozen; later preset edits do not rewrite this Content history'}</p>{error?<p className="mt-3 text-sm text-coral-dark">{error}</p>:null}{canManage&&items.length?<div className="mt-4 grid gap-3 sm:grid-cols-[11rem_minmax(0,1fr)_auto] sm:items-end"><FormField label={zh?'用途':'Usage'}><Select value={slot} onChange={e=>setSlot(e.target.value as typeof slot)}>{slots.map(value=><option key={value} value={value}>{slotText[value][zh?0:1]}</option>)}</Select></FormField><FormField label={zh?'剪辑规范':'Preset'}><Select value={preset} onChange={e=>setPreset(e.target.value)}>{items.map(item=><option key={item.id} value={item.id}>{item.name} · V{item.version_number}</option>)}</Select></FormField><Button disabled={busy||!preset} onClick={()=>void assign()}>{busy?<LoaderCircle className="size-4 animate-spin"/>:null}{zh?'套用规范':'Apply'}</Button></div>:null}<div className="mt-4 grid gap-2 sm:grid-cols-2">{snapshots.map(item=><div key={item.id} className="rounded-lg border border-line bg-canvas-raised p-3"><p className="text-xs font-bold text-coral">{slotText[item.usage_slot][zh?0:1]} · V{item.preset_version}</p><p className="mt-1 font-bold">{String(item.preset_snapshot.name??'Preset')}</p><p className="mt-1 text-xs text-ink-muted">{String(item.preset_snapshot.purpose??'')}</p></div>)}{!snapshots.length?<p className="text-sm text-ink-muted">{zh?'尚未选择制作规范':'No production presets selected'}</p>:null}</div></Card>
}
