import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { CheckCircle2, ExternalLink, FileVideo2, LoaderCircle, MessageSquareWarning, ShieldCheck } from 'lucide-react'
import { Button, Card, FormField, Input, Select, StatusBadge, Textarea } from '../../components/ui'
import type { ContentRecord } from './content-api'
import type { ContentContributorRecord } from './workflow-api'
import {
  approveStage, configureApprovalRequirement, overrideApproval, recordExternalApproval,
  requestRevision, sendToClientReview, startReview, startRevision, submitFinalMedia,
  submitFirstCut, submitRevision,
} from './review-api'
import type { ApprovalType, MediaInput, ReviewBundle } from './review-api'

interface Props { content: ContentRecord; bundle: ReviewBundle; contributors: ContentContributorRecord[]; currentUserId: string; workspaceRoles: string[]; canManage: boolean; onChanged: () => Promise<void> }
const stages: ApprovalType[] = ['topic','script','internal_video','client','final']
const label = (value: string) => value.split('_').map((part) => part[0]?.toUpperCase()+part.slice(1)).join(' ')
const formatDate = (value: string | null) => value ? new Date(value).toLocaleString('en-MY') : '—'
const emptyMedia: MediaInput = { externalUrl: '', localPath: '', nasPath: '', note: '' }

export function ReviewWorkspace({ content, bundle, contributors, currentUserId, workspaceRoles, canManage, onChanged }: Props) {
  const [media, setMedia] = useState<MediaInput>(emptyMedia); const [note, setNote] = useState('')
  const [reason, setReason] = useState('pacing'); const [reasonNotes, setReasonNotes] = useState('')
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const [external, setExternal] = useState({ name:'', channel:'whatsapp', decidedAt:'', note:'', evidence:'' })
  const reviewerOptions = contributors.filter((item) => item.status==='active' && item.contribution_role_code==='reviewer')
  const latestMedia = bundle.media[0]; const latestScript = bundle.scripts[0]
  const assignedEditor = contributors.some((item) => item.status==='active' && item.user_profile_id===currentUserId && item.contribution_role_code==='editor') && workspaceRoles.includes('Editor')
  const currentStage: ApprovalType | null = content.current_status==='internal_review' ? 'internal_video' : content.current_status==='client_review' ? (bundle.requirements.find((r)=>r.approval_type==='client'&&r.is_required&&r.status!=='approved') ? 'client' : 'final') : null
  const assignedReviewer = currentStage ? bundle.requirements.find((r)=>r.approval_type===currentStage)?.assigned_reviewer_user_id===currentUserId && reviewerOptions.some((r)=>r.user_profile_id===currentUserId) : false
  const target = { type: 'media_version', id: latestMedia?.id }
  const hasLocation = Boolean(media.externalUrl.trim() || media.localPath.trim() || media.nasPath.trim())
  async function run(key: string, action: () => Promise<unknown>) { setBusy(key); setError(null); try { await action(); setNote(''); setMedia(emptyMedia); await onChanged() } catch(caught) { setError(caught instanceof Error ? caught.message : 'Workflow action failed') } finally { setBusy(null) } }

  const primary = useMemo(() => {
    if (content.current_status==='editing' && bundle.revisions.some((r)=>r.status==='open')) return { label:'Submit Revision', enabled:assignedEditor&&hasLocation, run:()=>submitRevision(content.id,content.current_status,media,note) }
    if (content.current_status==='editing') return { label:'Submit First Cut', enabled:assignedEditor&&hasLocation, run:()=>submitFirstCut(content.id,content.current_status,media) }
    if (content.current_status==='first_cut_submitted') return { label:'Start Review', enabled:bundle.requirements.some((r)=>r.approval_type==='internal_video'&&r.assigned_reviewer_user_id===currentUserId)&&reviewerOptions.some((r)=>r.user_profile_id===currentUserId), run:()=>startReview(content.id,content.current_status,note) }
    if (content.current_status==='revision_required') return { label:'Start Revision', enabled:assignedEditor, run:()=>startRevision(content.id,content.current_status,note) }
    return null
  }, [assignedEditor,bundle.requirements,bundle.revisions,content,hasLocation,media,note,currentUserId,reviewerOptions])

  async function saveRequirement(event: FormEvent<HTMLFormElement>, type: ApprovalType) {
    event.preventDefault(); const form=new FormData(event.currentTarget); const required=form.get('required')==='yes'; const reviewer=String(form.get('reviewer')??'')||null
    await run(`requirement-${type}`,()=>configureApprovalRequirement(content.id,type,required,reviewer,String(form.get('notes')??'')))
  }
  return <div className="space-y-6">
    {error ? <div className="rounded-md border border-coral/30 bg-coral/8 p-3 text-sm text-coral-dark">{error}</div> : null}
    <Card className="overflow-hidden p-0"><div className="grid lg:grid-cols-[minmax(0,1fr)_18rem]"><section className="p-5 sm:p-6"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-coral">Primary action</p><h3 className="mt-3 font-display text-3xl font-semibold">{primary?.label ?? (assignedReviewer ? `Review ${label(currentStage ?? '')}` : 'Waiting for the next owner')}</h3><p className="mt-2 text-sm leading-6 text-ink-muted">Every action is checked against the current locked row, active assignment, and exact version target.</p>{['editing','client_review'].includes(content.current_status) ? <div className="mt-5 grid gap-3 sm:grid-cols-2"><Input placeholder="Drive / external URL" value={media.externalUrl} onChange={(e)=>setMedia({...media,externalUrl:e.target.value})}/><Input placeholder="Local path" value={media.localPath} onChange={(e)=>setMedia({...media,localPath:e.target.value})}/><Input placeholder="NAS path" value={media.nasPath} onChange={(e)=>setMedia({...media,nasPath:e.target.value})}/><Input placeholder="Version note" value={media.note} onChange={(e)=>setMedia({...media,note:e.target.value})}/></div> : null}<Textarea className="mt-4 min-h-20" placeholder="Action note" value={note} onChange={(e)=>setNote(e.target.value)}/><div className="mt-4 flex flex-wrap gap-2">{primary ? <Button disabled={!primary.enabled||busy!==null} onClick={()=>void run('primary',primary.run)}>{busy==='primary'?<LoaderCircle className="size-4 animate-spin"/>:<CheckCircle2 className="size-4"/>}{primary.label}</Button> : null}{content.current_status==='client_review' && assignedEditor && bundle.requirements.some((r)=>r.approval_type==='final'&&r.status==='pending') ? <Button disabled={!hasLocation||busy!==null} onClick={()=>void run('final',()=>submitFinalMedia(content.id,content.current_status,media))}><FileVideo2 className="size-4"/>Submit Final</Button>:null}</div></section><aside className="border-t border-line bg-canvas-raised p-5 lg:border-l lg:border-t-0"><p className="text-xs font-bold uppercase tracking-wider text-ink-faint">Current stage</p><p className="mt-3 font-display text-2xl font-semibold">{label(content.current_status)}</p><p className="mt-3 text-xs leading-5 text-ink-muted">No status dropdown. Stale duplicate actions are rejected.</p></aside></div></Card>

    <div className="grid gap-6 xl:grid-cols-2"><Card><div className="flex items-center justify-between"><div className="flex items-center gap-2"><FileVideo2 className="size-4 text-blue"/><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">Media versions</p></div><StatusBadge tone="info">Links only</StatusBadge></div>{bundle.media.length?<div className="mt-5 space-y-3">{bundle.media.map((item)=><article key={item.id} className="rounded-lg border border-line p-4"><div className="flex items-center justify-between"><p className="font-bold">V{item.version_number} · {label(item.version_type)}</p><time className="text-xs text-ink-faint">{formatDate(item.submitted_at)}</time></div><div className="mt-3 space-y-1 text-xs">{item.external_url?<a className="inline-flex items-center gap-1 font-bold text-blue hover:underline" href={item.external_url} target="_blank" rel="noreferrer">Open external media <ExternalLink className="size-3"/></a>:null}{item.local_path?<p>{item.local_path}</p>:null}{item.nas_path?<p>{item.nas_path}</p>:null}</div>{item.note?<p className="mt-3 text-sm text-ink-muted">{item.note}</p>:null}</article>)}</div>:<p className="mt-5 rounded-md border border-dashed border-line-strong p-4 text-sm text-ink-muted">No First Cut submitted.</p>}</Card>
    <Card><div className="flex items-center gap-2"><MessageSquareWarning className="size-4 text-coral"/><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">Revision history</p></div>{bundle.revisions.length?<div className="mt-5 space-y-3">{bundle.revisions.map((item)=><article key={item.id} className="rounded-lg border border-line p-4"><div className="flex justify-between gap-3"><p className="font-bold">{label(item.reason_code)}</p><StatusBadge tone={item.status==='open'?'warning':'success'}>{item.status}</StatusBadge></div><p className="mt-2 text-sm leading-6 text-ink-muted">{item.reason_notes||'No additional notes.'}</p><p className="mt-3 text-xs text-ink-faint">{label(item.review_scope)} · {formatDate(item.requested_at)}{item.resolved_at?` → ${formatDate(item.resolved_at)}`:''}</p></article>)}</div>:<p className="mt-5 rounded-md border border-dashed border-line-strong p-4 text-sm text-ink-muted">No revision requests.</p>}</Card></div>

    {assignedReviewer && latestMedia ? <Card><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-gold"/><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">Reviewer decision · {label(currentStage ?? '')}</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><FormField label="Decision note" htmlFor="decision-note"><Textarea id="decision-note" value={note} onChange={(e)=>setNote(e.target.value)}/></FormField><div className="mt-3 flex gap-2"><Button disabled={!target.id||busy!==null} onClick={()=>void run('approve',()=>approveStage(content.id,currentStage!,target.type,target.id!,content.current_status,note,''))}>Approve exact version</Button><Button variant="secondary" disabled={busy!==null} onClick={()=>void run('revision',()=>requestRevision(content.id,content.current_status,reason,reasonNotes,note))}>Request revision</Button></div></div><div className="grid gap-3"><Select value={reason} onChange={(e)=>setReason(e.target.value)}>{['subtitle','pacing','hook','visual','brand','information','client_request','audio','other'].map((value)=><option key={value} value={value}>{label(value)}</option>)}</Select><Textarea placeholder="Revision reason notes" value={reasonNotes} onChange={(e)=>setReasonNotes(e.target.value)}/></div></div>{currentStage==='internal_video' && bundle.requirements.some((r)=>r.approval_type==='internal_video'&&r.status==='approved')?<Button className="mt-4" variant="secondary" onClick={()=>void run('send-client',()=>sendToClientReview(content.id,content.current_status,note))}>Send to Client Review</Button>:null}</Card>:null}

    {(workspaceRoles.includes('Super Admin')||workspaceRoles.includes('Internal Manager')) && currentStage && target.id ? <Card tone="quiet"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">Record external approval</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Input placeholder="Approver name" value={external.name} onChange={(e)=>setExternal({...external,name:e.target.value})}/><Select value={external.channel} onChange={(e)=>setExternal({...external,channel:e.target.value})}><option value="whatsapp">WhatsApp</option><option value="face_to_face">Face-to-face</option><option value="call">Call</option><option value="other">Other</option></Select><Input type="datetime-local" value={external.decidedAt} onChange={(e)=>setExternal({...external,decidedAt:e.target.value})}/><Input placeholder="Evidence URL (internal)" value={external.evidence} onChange={(e)=>setExternal({...external,evidence:e.target.value})}/><Input placeholder="Record note" value={external.note} onChange={(e)=>setExternal({...external,note:e.target.value})}/><Button disabled={!external.name||!external.decidedAt||busy!==null} onClick={()=>void run('external',()=>recordExternalApproval(content.id,currentStage,target.type,target.id!,content.current_status,{...external,decidedAt:new Date(external.decidedAt).toISOString()}))}>Record approval</Button></div><p className="mt-3 text-xs text-ink-muted">Evidence is internal by default. Recorder and external approver remain separate identities.</p></Card>:null}

    {canManage ? <Card><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">Approval requirements</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{stages.map((type)=>{const item=bundle.requirements.find((r)=>r.approval_type===type);return <form key={type} className="rounded-lg border border-line p-4" onSubmit={(e)=>void saveRequirement(e,type)}><div className="flex items-center justify-between"><p className="font-bold">{label(type)}</p><StatusBadge>{item?.status??'not configured'}</StatusBadge></div><div className="mt-3 grid gap-3"><Select name="required" defaultValue={item?.is_required?'yes':'no'}><option value="no">Not required</option><option value="yes">Required</option></Select><Select name="reviewer" defaultValue={item?.assigned_reviewer_user_id??''}><option value="">Select assigned Reviewer</option>{reviewerOptions.map((person)=><option key={person.user_profile_id} value={person.user_profile_id}>{person.display_name}</option>)}</Select><Input name="notes" defaultValue={item?.notes??''} placeholder="Requirement note"/><div className="flex flex-wrap gap-2"><Button size="sm" type="submit" disabled={busy!==null}>Save requirement</Button>{(['topic','script'] as ApprovalType[]).includes(type) && item?.is_required && item.status==='pending' && item.assigned_reviewer_user_id===currentUserId && reviewerOptions.some((person)=>person.user_profile_id===currentUserId) && (type==='topic'||latestScript) ? <Button size="sm" type="button" variant="secondary" disabled={busy!==null} onClick={()=>void run(`approve-${type}`,()=>approveStage(content.id,type,type==='topic'?'content':'script_version',type==='topic'?content.id:latestScript!.id,content.current_status,`Approved ${label(type)} checkpoint`,''))}>Approve checkpoint</Button> : null}{workspaceRoles.includes('Super Admin')&&item?.is_required&& !['approved','waived'].includes(item.status)?<Button size="sm" type="button" variant="ghost" onClick={()=>{const reason=window.prompt('Override reason (required):')?.trim();if(reason)void run(`override-${type}`,()=>overrideApproval(item.id,reason))}}>Override</Button>:null}</div></div></form>})}</div></Card>:null}

    <Card><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">Approval history</p>{bundle.approvals.length?<div className="mt-5 space-y-3">{bundle.approvals.map((item)=><div key={item.id} className="flex flex-wrap items-start justify-between gap-3 rounded-md border border-line p-3"><div><p className="font-bold">{label(item.approval_type)} · {label(item.result)}</p><p className="mt-1 text-xs text-ink-muted">{item.external_approver_name?`${item.external_approver_name} via ${label(item.channel)}`:'Internal assigned reviewer'} · exact {label(item.target_type)}</p></div><time className="text-xs text-ink-faint">{formatDate(item.decided_at)}</time></div>)}</div>:<p className="mt-5 text-sm text-ink-muted">No approval decisions recorded.</p>}</Card>
  </div>
}
