import { ArrowUpRight, CalendarDays, ChevronRight } from 'lucide-react'
import { StatusBadge } from '../../components/ui'
import { useI18n } from '../i18n/i18n'
import { enumLabel, formatWorkspaceDate } from '../i18n/labels'
import type { ResearchCatalog, IdeaRecord, IdeaStatus } from './research-api'
import { getNextActionLabel } from './idea-planner'

function tone(status:IdeaStatus){if(status==='approved'||status==='converted')return'success' as const;if(status==='rejected')return'critical' as const;if(status==='evaluating')return'warning' as const;return'neutral' as const}
function nextAction(idea:IdeaRecord,zh:boolean){if(idea.status==='converted')return zh?'打开制作内容':'Open Production Content';const english=getNextActionLabel(idea);if(!zh)return english;return({new:'开始评估',evaluating:'确认选题',approved:'转入制作',rejected:'重新评估',archived:'重新评估'} as Record<string,string>)[idea.status]??'查看详情'}
export function IdeaPlannerView({ideas,catalog,onSelect,selectedIds=[],onToggle}:{ideas:IdeaRecord[];catalog:ResearchCatalog;onSelect:(idea:IdeaRecord)=>void;selectedIds?:string[];onToggle?:(ideaId:string,checked:boolean)=>void}){
 const{language}=useI18n();const zh=language==='zh-CN';const statusCell=(idea:IdeaRecord)=><div className="flex flex-wrap items-center gap-1.5"><StatusBadge tone={tone(idea.status)}>{idea.status==='converted'?(zh?'已进入制作':'In Production'):enumLabel(idea.status,language)}</StatusBadge>{idea.linked_content_status?<StatusBadge tone="warning">{enumLabel(idea.linked_content_status,language)}</StatusBadge>:null}</div>
 return <><div data-testid="idea-planner-desktop" className="hidden max-h-[68vh] overflow-auto lg:block"><table className="w-full min-w-[68rem] border-collapse text-left"><thead className="sticky top-0 z-10 border-b border-line bg-canvas-raised text-[.68rem] font-extrabold uppercase tracking-wider text-ink-faint"><tr><th className="w-11 px-3 py-3"><span className="sr-only">Select</span></th><th className="w-32 px-4 py-3">{zh?'计划日期':'Planned Date'}</th><th className="px-4 py-3">{zh?'选题标题':'Idea Title'}</th><th className="w-32 px-4 py-3">{zh?'分类':'Category'}</th><th className="w-56 px-4 py-3">{zh?'状态':'Status'}</th><th className="w-20 px-4 py-3">{zh?'优先级':'Priority'}</th><th className="w-36 px-4 py-3">{zh?'负责人':'Owner'}</th><th className="w-20 px-4 py-3 text-center">{zh?'来源':'Sources'}</th><th className="w-40 px-4 py-3">{zh?'下一步':'Next Action'}</th></tr></thead><tbody className="divide-y divide-line">{ideas.map(idea=><tr key={idea.id} tabIndex={0} onClick={()=>onSelect(idea)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onSelect(idea)}} className="group cursor-pointer bg-paper hover:bg-canvas-raised focus:bg-canvas-raised"><td className="px-3 py-3"><input type="checkbox" aria-label={`Select ${idea.title}`} checked={selectedIds.includes(idea.id)} disabled={idea.status==='converted'||idea.status==='archived'} onClick={e=>e.stopPropagation()} onChange={e=>onToggle?.(idea.id,e.target.checked)} className="size-4 accent-coral"/></td><td className="px-4 py-3 font-mono text-xs font-bold">{formatWorkspaceDate(idea.planned_date,language)}</td><td className="px-4 py-3"><p className="line-clamp-2 font-bold group-hover:text-coral-dark">{idea.title}</p></td><td className="px-4 py-3 text-sm text-ink-soft">{catalog.categories.find(c=>c.id===idea.category_id)?.name??'—'}</td><td className="px-4 py-3">{statusCell(idea)}</td><td className="px-4 py-3"><StatusBadge>{enumLabel(idea.priority,language)}</StatusBadge></td><td className="max-w-36 truncate px-4 py-3 text-sm">{idea.owner_name||idea.creator_name||(zh?'未分配':'Unassigned')}</td><td className="px-4 py-3 text-center font-bold text-ink-muted">{idea.referenceIds.length}</td><td className="px-4 py-3 text-sm font-bold text-blue"><span className="inline-flex items-center gap-1.5">{nextAction(idea,zh)}<ArrowUpRight className="size-3.5"/></span></td></tr>)}</tbody></table></div>
 <div data-testid="idea-planner-mobile" className="divide-y divide-line lg:hidden">{ideas.map(idea=><button key={idea.id} onClick={()=>onSelect(idea)} className="grid w-full grid-cols-[4.5rem_minmax(0,1fr)_auto] gap-3 px-4 py-3.5 text-left hover:bg-canvas-raised"><div><p className="font-mono text-xs font-extrabold text-coral-dark">{formatWorkspaceDate(idea.planned_date,language,{year:undefined})}</p></div><div className="min-w-0"><p className="line-clamp-2 text-sm font-bold">{idea.title}</p><div className="mt-2 flex flex-wrap gap-1.5">{statusCell(idea)}<StatusBadge>{enumLabel(idea.priority,language)}</StatusBadge></div></div><ChevronRight className="size-4 text-ink-faint"/></button>)}</div></>
}
export function IdeaBoardView({ideas,onSelect}:{ideas:IdeaRecord[];onSelect:(idea:IdeaRecord)=>void}){const{language}=useI18n();const zh=language==='zh-CN';const columns:IdeaStatus[]=['new','evaluating','approved','converted','rejected','archived'];return <div className="flex gap-3 overflow-x-auto p-3" data-testid="idea-board">{columns.map(status=>{const rows=ideas.filter(i=>i.status===status);return <section key={status} className="w-72 shrink-0 rounded-xl border border-line bg-canvas-raised/55"><header className="flex items-center justify-between border-b border-line px-3 py-3"><p className="text-xs font-extrabold">{enumLabel(status,language)}</p><span className="rounded-full bg-paper px-2 text-xs font-bold">{rows.length}</span></header><div className="space-y-2 p-2">{rows.map(idea=><button key={idea.id} onClick={()=>onSelect(idea)} className="w-full rounded-lg border border-line bg-paper p-3 text-left hover:border-coral/40"><div className="flex items-center gap-2 text-xs text-ink-faint"><CalendarDays className="size-3.5"/>{formatWorkspaceDate(idea.planned_date,language,{year:undefined})}</div><p className="mt-2 line-clamp-3 text-sm font-bold">{idea.title}</p>{idea.linked_content_status?<p className="mt-2 text-xs font-bold text-gold-dark">{zh?'制作：':'Production: '}{enumLabel(idea.linked_content_status,language)}</p>:null}</button>)}{!rows.length?<p className="py-6 text-center text-xs text-ink-faint">{zh?'暂无选题':'No Ideas'}</p>:null}</div></section>})}</div>}