import { ArrowUpRight, CalendarDays, ChevronRight } from 'lucide-react'
import { StatusBadge } from '../../components/ui'
import { useI18n } from '../i18n/i18n'
import { enumLabel, formatWorkspaceDate } from '../i18n/labels'
import type { ResearchCatalog, IdeaRecord, PlanningStatus } from './research-api'
import { getNextActionLabel, planningStatusLabel, productionProgressLabel } from './idea-planner'

function tone(status: PlanningStatus) {
  if (status === 'confirmed') return 'success' as const
  if (status === 'rejected') return 'critical' as const
  if (status === 'evaluating' || status === 'paused') return 'warning' as const
  return 'neutral' as const
}
function shootDate(idea: IdeaRecord) { return idea.linked_content_shoot_scheduled_at || idea.shoot_planned_at }
function dateTime(value: string | null, language: 'zh-CN' | 'en') {
  if (!value) return null
  return new Intl.DateTimeFormat(language === 'zh-CN' ? 'zh-CN' : 'en-MY', { timeZone: 'Asia/Kuala_Lumpur', day: '2-digit', month: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(value))
}

export function IdeaPlannerView({ideas,catalog,onSelect,selectedIds=[],onToggle}:{ideas:IdeaRecord[];catalog:ResearchCatalog;onSelect:(idea:IdeaRecord)=>void;selectedIds?:string[];onToggle?:(ideaId:string,checked:boolean)=>void}) {
  const {language}=useI18n(); const zh=language==='zh-CN'
  const statusCell=(idea:IdeaRecord)=>{
    const progress=idea.status==='converted'?productionProgressLabel(idea.linked_content_status,language):null
    return <div className="space-y-1.5"><div className="flex items-center gap-1.5"><span className="text-[.68rem] font-bold text-ink-faint">{zh?'策划':'Plan'}</span><StatusBadge tone={tone(idea.planning_status)}>{planningStatusLabel(idea.planning_status,language)}</StatusBadge></div>{progress?<div className="flex items-center gap-1.5"><span className="text-[.68rem] font-bold text-ink-faint">{zh?'制作':'Prod.'}</span><StatusBadge tone="warning">{progress}</StatusBadge></div>:null}</div>
  }
  return <>
    <div data-testid="idea-planner-desktop" className="hidden max-h-[68vh] overflow-auto lg:block"><table className="w-full min-w-[72rem] border-collapse text-left text-[.925rem]"><thead className="sticky top-0 z-10 border-b border-line bg-canvas-raised text-xs font-extrabold uppercase tracking-wider text-ink-faint"><tr><th className="w-11 px-3 py-3"><span className="sr-only">Select</span></th><th className="w-40 px-4 py-3">{zh?'目标发布日期':'Target Publish Date'}</th><th className="px-4 py-3">{zh?'选题标题':'Idea Title'}</th><th className="w-32 px-4 py-3">{zh?'分类':'Category'}</th><th className="w-56 px-4 py-3">{zh?'状态':'Status'}</th><th className="w-24 px-4 py-3">{zh?'优先级':'Priority'}</th><th className="w-36 px-4 py-3">{zh?'负责人':'Owner'}</th><th className="w-20 px-4 py-3 text-center">{zh?'来源':'Sources'}</th><th className="w-40 px-4 py-3">{zh?'下一步':'Next Action'}</th></tr></thead><tbody className="divide-y divide-line">{ideas.map(idea=><tr key={idea.id} tabIndex={0} onClick={()=>onSelect(idea)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onSelect(idea)}} className="group cursor-pointer bg-paper hover:bg-canvas-raised focus:bg-canvas-raised"><td className="px-3 py-3"><input type="checkbox" aria-label={`Select ${idea.title}`} checked={selectedIds.includes(idea.id)} disabled={idea.planning_status==='archived'} onClick={e=>e.stopPropagation()} onChange={e=>onToggle?.(idea.id,e.target.checked)} className="size-4 accent-coral"/></td><td className="px-4 py-3"><p className="font-mono text-sm font-extrabold">{formatWorkspaceDate(idea.planned_date,language,{year:undefined})}</p><p className="mt-1 text-xs text-ink-muted">{zh?'发布':'Publish'}</p>{shootDate(idea)?<p className="mt-2 text-xs font-bold text-blue">{dateTime(shootDate(idea),language)} · {zh?'拍摄':'Shoot'}</p>:null}</td><td className="px-4 py-3"><p className="line-clamp-2 font-bold leading-6 group-hover:text-coral-dark">{idea.title}</p></td><td className="px-4 py-3 text-ink-soft">{catalog.categories.find(c=>c.id===idea.category_id)?.name??'—'}</td><td className="px-4 py-3">{statusCell(idea)}</td><td className="px-4 py-3"><StatusBadge>{enumLabel(idea.priority,language)}</StatusBadge></td><td className="max-w-36 truncate px-4 py-3">{idea.owner_name||idea.creator_name||(zh?'未分配':'Unassigned')}</td><td className="px-4 py-3 text-center font-bold text-ink-muted">{idea.referenceIds.length}</td><td className="px-4 py-3 font-bold text-blue"><span className="inline-flex items-center gap-1.5">{getNextActionLabel(idea,language)}<ArrowUpRight className="size-3.5"/></span></td></tr>)}</tbody></table></div>
    <div data-testid="idea-planner-mobile" className="divide-y divide-line lg:hidden">{ideas.map(idea=><button key={idea.id} onClick={()=>onSelect(idea)} className="grid w-full grid-cols-[4.8rem_minmax(0,1fr)_auto] gap-3 px-4 py-3.5 text-left hover:bg-canvas-raised"><div><p className="font-mono text-xs font-extrabold text-coral-dark">{formatWorkspaceDate(idea.planned_date,language,{year:undefined})}</p><p className="mt-1 text-[.65rem] text-ink-faint">{zh?'目标发布':'Publish'}</p></div><div className="min-w-0"><p className="line-clamp-2 text-[.925rem] font-bold leading-5">{idea.title}</p><div className="mt-2 flex flex-wrap gap-1.5"><StatusBadge tone={tone(idea.planning_status)}>{planningStatusLabel(idea.planning_status,language)}</StatusBadge>{idea.status==='converted'&&idea.linked_content_status?<StatusBadge tone="warning">{productionProgressLabel(idea.linked_content_status,language)}</StatusBadge>:null}<StatusBadge>{enumLabel(idea.priority,language)}</StatusBadge></div>{shootDate(idea)?<p className="mt-2 text-xs text-blue">{zh?'拍摄':'Shoot'} · {dateTime(shootDate(idea),language)}</p>:null}</div><ChevronRight className="size-4 text-ink-faint"/></button>)}</div>
  </>
}

export function IdeaBoardView({ideas,onSelect}:{ideas:IdeaRecord[];onSelect:(idea:IdeaRecord)=>void}) {
  const {language}=useI18n(); const zh=language==='zh-CN'; const columns:PlanningStatus[]=['new','evaluating','confirmed','paused','rejected','archived']
  return <div className="flex gap-3 overflow-x-auto p-3" data-testid="idea-board">{columns.map(status=>{const rows=ideas.filter(i=>i.planning_status===status);return <section key={status} className="w-72 shrink-0 rounded-xl border border-line bg-canvas-raised/55"><header className="flex items-center justify-between border-b border-line px-3 py-3"><p className="text-xs font-extrabold">{planningStatusLabel(status,language)}</p><span className="rounded-full bg-paper px-2 text-xs font-bold">{rows.length}</span></header><div className="space-y-2 p-2">{rows.map(idea=><button key={idea.id} onClick={()=>onSelect(idea)} className="w-full rounded-lg border border-line bg-paper p-3 text-left hover:border-coral/40"><div className="flex items-center gap-2 text-xs text-ink-faint"><CalendarDays className="size-3.5"/>{zh?'目标发布':'Target publish'} · {formatWorkspaceDate(idea.planned_date,language,{year:undefined})}</div><p className="mt-2 line-clamp-3 text-sm font-bold">{idea.title}</p>{idea.status==='converted'&&idea.linked_content_status?<p className="mt-2 text-xs font-bold text-gold-dark">{zh?'制作：':'Production: '}{productionProgressLabel(idea.linked_content_status,language)}</p>:null}</button>)}{!rows.length?<p className="py-6 text-center text-xs text-ink-faint">{zh?'暂无选题':'No Ideas'}</p>:null}</div></section>})}</div>
}