import { supabase } from '../../lib/supabase'

export type EquipmentProposalStatus='draft'|'pending_review'|'viewed'|'approved'|'paused'|'rejected'|'purchased'
export type EquipmentPriority='low'|'medium'|'high'
export interface EquipmentProposalRecord{id:string;workspace_id:string;title:string;upgrade_reason:string|null;current_problem:string|null;use_cases:string[];expected_value:string|null;budget:number|null;priority:EquipmentPriority;desired_purchase_date:string|null;reference_urls:string[];boss_feedback:string|null;status:EquipmentProposalStatus;proposed_by:string;proposer_name:string;decided_by:string|null;decider_name:string|null;decided_at:string|null;purchased_at:string|null;created_at:string;updated_at:string}
function fail(error:{message:string}|null){if(error)throw new Error(error.message)}
export async function loadEquipmentProposals(workspaceId:string){const{data,error}=await supabase.rpc('list_equipment_proposals',{target_workspace_id:workspaceId});fail(error);return(data??[])as EquipmentProposalRecord[]}
export async function saveEquipmentProposal(workspaceId:string,value:{id?:string;title:string;upgradeReason:string;currentProblem:string;useCases:string[];expectedValue:string;budget:string;priority:EquipmentPriority;desiredPurchaseDate:string;referenceUrls:string[];status:'draft'|'pending_review'}){const{data,error}=await supabase.rpc('save_equipment_proposal',{target_proposal_id:value.id??null,target_workspace_id:workspaceId,target_title:value.title,target_upgrade_reason:value.upgradeReason,target_current_problem:value.currentProblem,target_use_cases:value.useCases,target_expected_value:value.expectedValue,target_budget:value.budget.trim()?Number(value.budget):null,target_priority:value.priority,target_desired_purchase_date:value.desiredPurchaseDate||null,target_reference_urls:value.referenceUrls,target_status:value.status});fail(error);return data as string}
export async function decideEquipmentProposal(id:string,decision:'viewed'|'approved'|'paused'|'rejected'|'purchased',feedback:string){const{error}=await supabase.rpc('decide_equipment_proposal',{target_proposal_id:id,target_decision:decision,target_feedback:feedback});fail(error)}
