import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowRight, BarChart3, FilterX, LoaderCircle } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button, Card, Input, Select, StatusBadge } from '../components/ui'
import { useAuth } from '../features/auth/auth-context'
import { loadContentCatalog } from '../features/content/content-api'
import { loadAnalyticsQueue } from '../features/publishing/publishing-api'
import type { AnalyticsSnapshotRecord, PlatformRecord, PublicationRecord, SocialAccountRecord } from '../features/publishing/publishing-api'
import type { ClientRecord } from '../features/admin/admin-api'

interface Queue {publications:PublicationRecord[];snapshots:AnalyticsSnapshotRecord[];platforms:PlatformRecord[];accounts:SocialAccountRecord[];contents:Array<{id:string;client_id:string;content_code:string;title:string}>}
const empty:Queue={publications:[],snapshots:[],platforms:[],accounts:[],contents:[]}
const label=(v:string)=>v.split('_').map((p)=>p[0]?.toUpperCase()+p.slice(1)).join(' ')
const metric=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('en-MY')

export function AnalyticsPage(){
  const{workspace}=useAuth();const navigate=useNavigate();const[data,setData]=useState<Queue>(empty);const[clients,setClients]=useState<ClientRecord[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
  const[client,setClient]=useState('all');const[platform,setPlatform]=useState('all');const[from,setFrom]=useState('');const[to,setTo]=useState('')
  const hasAccess=workspace?.roles.some((r)=>!['Client Admin','Client Viewer'].includes(r))??false
  const refresh=useCallback(async()=>{if(!workspace||!hasAccess)return;setLoading(true);setError(null);try{const[q,c]=await Promise.all([loadAnalyticsQueue(workspace.id),loadContentCatalog(workspace.id)]);setData(q);setClients(c.clients)}catch(caught){setError(caught instanceof Error?caught.message:'Could not load Analytics')}finally{setLoading(false)}},[hasAccess,workspace])
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh])
  const rows=useMemo(()=>data.publications.filter((p)=>p.status==='published').map((publication)=>{const snapshots=data.snapshots.filter((s)=>s.publication_id===publication.id);return{publication,latest:snapshots[0],snapshots,content:data.contents.find((c)=>c.id===publication.content_id),platform:data.platforms.find((x)=>x.id===publication.platform_id),account:data.accounts.find((a)=>a.id===publication.social_account_id)}}).filter((row)=>{if(client!=='all'&&row.publication.client_id!==client)return false;if(platform!=='all'&&row.publication.platform_id!==platform)return false;const date=row.latest?.captured_at??row.publication.published_at;if(from&&date&&new Date(date)<new Date(`${from}T00:00:00`))return false;if(to&&date&&new Date(date)>new Date(`${to}T23:59:59`))return false;return true}),[client,data,from,platform,to])
  if(!hasAccess)return <Card className="mx-auto mt-12 max-w-2xl text-center"><BarChart3 className="mx-auto size-9 text-coral"/><h2 className="mt-4 font-display text-3xl font-semibold">Internal Analytics access required</h2><p className="mt-3 text-ink-muted">Client roles do not receive the production analytics workspace in this phase.</p></Card>
  return <div className="page-enter space-y-6"><header className="border-b border-line pb-6"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-coral">Manual analytics queue</p><h2 className="mt-2 max-w-4xl font-display text-4xl font-semibold sm:text-5xl">See what is missing, not a decorative dashboard.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-muted">Publication-level Facebook and Xiaohongshu snapshots, isolated by Client. Blank metrics remain unknown—not zero.</p></header>{error?<div className="rounded-md border border-coral/30 bg-coral/8 p-3 text-sm text-coral-dark">{error}</div>:null}
  <Card className="p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_10rem_10rem_auto]"><Select value={client} onChange={(e)=>setClient(e.target.value)}><option value="all">All Clients</option>{clients.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select value={platform} onChange={(e)=>setPlatform(e.target.value)}><option value="all">All Platforms</option>{data.platforms.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Input type="date" aria-label="From date" value={from} onChange={(e)=>setFrom(e.target.value)}/><Input type="date" aria-label="To date" value={to} onChange={(e)=>setTo(e.target.value)}/><Button variant="ghost" onClick={()=>{setClient('all');setPlatform('all');setFrom('');setTo('')}}><FilterX className="size-4"/>Clear</Button></div></Card>
  <Card className="overflow-hidden p-0">{loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="size-7 animate-spin text-coral"/></div>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[70rem] text-left text-sm"><thead className="bg-canvas-raised text-[.68rem] uppercase tracking-[.14em] text-ink-muted"><tr><th className="px-5 py-3">Content / Publication</th><th className="px-4 py-3">Platform / Account</th><th className="px-4 py-3">Coverage</th><th className="px-4 py-3">Latest capture</th><th className="px-4 py-3">Views</th><th className="px-4 py-3">Reach</th><th className="px-4 py-3">Likes</th><th className="px-5 py-3"></th></tr></thead><tbody>{rows.map(({publication,latest,snapshots,content,platform,account})=>{const types=new Set(snapshots.map((s)=>s.snapshot_type));const missing=['24h','7d','30d'].filter((x)=>!types.has(x as never));return <tr key={publication.id} className="border-t border-line"><td className="px-5 py-4"><p className="font-mono text-xs font-bold text-coral">{content?.content_code}</p><p className="mt-1 max-w-sm font-bold">{content?.title??'Content'}</p></td><td className="px-4 py-4"><p className="font-bold">{platform?.name}</p><p className="mt-1 text-xs text-ink-muted">{account?.account_name} · {account?.account_handle}</p></td><td className="px-4 py-4">{missing.length?<StatusBadge tone="warning">Missing {missing.join(' / ')}</StatusBadge>:<StatusBadge tone="success">Core windows captured</StatusBadge>}</td><td className="px-4 py-4 text-xs">{latest?`${label(latest.snapshot_type)} · ${new Date(latest.captured_at).toLocaleString('en-MY')}`:'No snapshot'}</td><td className="px-4 py-4 font-mono">{metric(latest?.views_or_plays)}</td><td className="px-4 py-4 font-mono">{metric(latest?.reach)}</td><td className="px-4 py-4 font-mono">{metric(latest?.likes)}</td><td className="px-5 py-4"><Button size="sm" variant="ghost" onClick={()=>navigate(`/content/${publication.content_id}`)}>Open <ArrowRight className="size-3.5"/></Button></td></tr>})}</tbody></table></div>:<div className="grid min-h-72 place-items-center p-8 text-center"><div><BarChart3 className="mx-auto size-9 text-ink-faint"/><h3 className="mt-4 font-display text-2xl font-semibold">No published Publications in this view</h3><p className="mt-2 text-sm text-ink-muted">Published records will appear here for manual snapshot follow-up.</p></div></div>}</Card></div>
}
