import{useCallback,useEffect,useMemo,useState}from'react'
import{ArrowLeft,ArrowRight,CalendarDays,LoaderCircle}from'lucide-react'
import{useNavigate}from'react-router-dom'
import{Button,Card}from'../components/ui'
import{useAuth}from'../features/auth/auth-context'
import{loadCalendarEvents}from'../features/pilot/pilot-api'
import type{CalendarEvent}from'../features/pilot/pilot-api'
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
export function CalendarPage(){const{workspace}=useAuth();const navigate=useNavigate();const[month,setMonth]=useState(()=>new Date(2026,8,1));const[events,setEvents]=useState<CalendarEvent[]>([]);const[loading,setLoading]=useState(true);const from=iso(new Date(month.getFullYear(),month.getMonth(),1));const to=iso(new Date(month.getFullYear(),month.getMonth()+1,0));const refresh=useCallback(async()=>{if(!workspace)return;setLoading(true);setEvents(await loadCalendarEvents(workspace.id,from,to));setLoading(false)},[from,to,workspace]);useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh]);const days=useMemo(()=>Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,index)=>iso(new Date(month.getFullYear(),month.getMonth(),index+1))),[month]);const open=(event:CalendarEvent)=>navigate(event.entity_type==='idea'?`/ideas?idea=${event.entity_id}`:`/content/${event.entity_id}`);const label=new Intl.DateTimeFormat('zh-CN',{month:'long',year:'numeric',timeZone:'Asia/Kuala_Lumpur'}).format(month)
return <div className="page-enter space-y-5"><header className="flex items-end justify-between border-b border-line pb-5"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-coral">Plan · Shoot · Publish</p><h2 className="mt-2 font-display text-4xl font-semibold">日历</h2><p className="mt-2 text-sm text-ink-muted">自动来自内容计划、拍摄与发布资料，不需要重复建立 event。</p></div><div className="flex items-center gap-2"><Button size="icon" variant="secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ArrowLeft className="size-4"/></Button><span className="min-w-32 text-center font-bold">{label}</span><Button size="icon" variant="secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ArrowRight className="size-4"/></Button></div></header>{loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="size-7 animate-spin text-coral"/></div>:<><Card data-testid="calendar-month" className="hidden overflow-hidden p-0 lg:block"><div className="grid grid-cols-7 border-b border-line bg-canvas-raised text-center text-xs font-extrabold uppercase text-ink-faint">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><div key={day} className="p-3">{day}</div>)}</div><div className="grid grid-cols-7">{Array.from({length:new Date(month.getFullYear(),month.getMonth(),1).getDay()}).map((_,i)=><div key={`blank-${i}`} className="min-h-32 border-b border-r border-line bg-canvas-raised/35"/>)}{days.map(day=><div key={day} className="min-h-32 border-b border-r border-line p-2"><p className="text-xs font-bold text-ink-faint">{Number(day.slice(-2))}</p><div className="mt-2 space-y-1">{events.filter(e=>e.event_at.slice(0,10)===day).map(event=><button key={event.event_key} onClick={()=>open(event)} className="w-full rounded border border-line bg-paper p-1.5 text-left text-[.68rem] hover:border-coral"><span className="font-extrabold text-coral">{event.event_type}</span><span className="mt-1 block line-clamp-2 font-bold">{event.title}</span></button>)}</div></div>)}</div></Card><Card data-testid="calendar-agenda" className="p-0 lg:hidden">{events.length?<div className="divide-y divide-line">{events.map(event=><button key={event.event_key} onClick={()=>open(event)} className="grid w-full grid-cols-[5rem_1fr_auto] gap-3 p-4 text-left"><div><p className="font-mono text-sm font-bold text-coral">{event.event_at.slice(5,10)}</p><p className="mt-1 text-xs text-ink-faint">{event.event_type}</p></div><div><p className="font-bold">{event.title}</p><p className="mt-1 text-xs text-ink-muted">{event.client_name} · {event.status}</p></div><ArrowRight className="size-4 text-ink-faint"/></button>)}</div>:<div className="p-8 text-center"><CalendarDays className="mx-auto size-8 text-ink-faint"/><p className="mt-3 font-bold">这个月还没有排期</p><p className="mt-2 text-sm text-ink-muted">在内容计划设置 Planned Date 后会自动出现。</p></div>}</Card></>}</div>}
