import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, Clapperboard, FileText, LoaderCircle, Pencil, Video } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button, Card, StatusBadge } from '../components/ui'
import { useAuth } from '../features/auth/auth-context'
import { ContentFormDrawer } from '../features/content/ContentFormDrawer'
import { ProductionWorkspace } from '../features/content/ProductionWorkspace'
import { ReviewWorkspace } from '../features/content/ReviewWorkspace'
import { ScriptWorkspace } from '../features/content/ScriptWorkspace'
import { TimelineWorkspace } from '../features/content/TimelineWorkspace'
import { loadContentCatalog, loadContentDetail } from '../features/content/content-api'
import type { ContentCatalog, ContentDetail } from '../features/content/content-api'
import { loadReviewBundle } from '../features/content/review-api'
import type { ReviewBundle } from '../features/content/review-api'
import { loadWorkflowBundle } from '../features/content/workflow-api'
import type { WorkflowBundle } from '../features/content/workflow-api'
import { enumLabel, formatWorkspaceDate } from '../features/i18n/labels'
import { useI18n } from '../features/i18n/i18n'
import { BossMode } from '../features/pilot/BossMode'
import { ShootingBrief } from '../features/pilot/ShootingBrief'
import { PublishingWorkspace } from '../features/publishing/PublishingWorkspace'
import { loadPublishingBundle } from '../features/publishing/publishing-api'
import type { PublishingBundle } from '../features/publishing/publishing-api'
const emptyCatalog:ContentCatalog={clients:[],categories:[],campaigns:[]}
const tabs=['brief','script','production','review','publishing','activity'] as const
type Tab=typeof tabs[number]
export function ContentDetailPage(){
 const{contentId}=useParams();const{workspace,session}=useAuth();const navigate=useNavigate();const{language}=useI18n();const zh=language==='zh-CN';const[detail,setDetail]=useState<ContentDetail|null>(null);const[workflow,setWorkflow]=useState<WorkflowBundle|null>(null);const[review,setReview]=useState<ReviewBundle|null>(null);const[publishing,setPublishing]=useState<PublishingBundle|null>(null);const[catalog,setCatalog]=useState<ContentCatalog>(emptyCatalog);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[editing,setEditing]=useState(false);const[boss,setBoss]=useState(false);const[tab,setTab]=useState<Tab>('brief')
 const isSuper=workspace?.roles.includes('Super Admin')??false;const isManager=workspace?.roles.includes('Internal Manager')??false;const canManage=isSuper||isManager||workspace?.roles.includes('Strategist / Content Planner');const allowed=workspace?.roles.some(r=>!['Client Admin','Client Viewer'].includes(r))??false
 const refresh=useCallback(async()=>{if(!workspace||!contentId||!allowed)return;setLoading(true);setError(null);try{const[d,c,w,r,p]=await Promise.all([loadContentDetail(workspace.id,contentId),loadContentCatalog(workspace.id),loadWorkflowBundle(contentId),loadReviewBundle(contentId),loadPublishingBundle(contentId)]);setDetail(d);setCatalog(c);setWorkflow(w);setReview(r);setPublishing(p);if(!d)setError(zh?'找不到内容或无权访问。':'Content not found or outside your access.')}catch(e){setError(e instanceof Error?e.message:'Unable to load Content')}finally{setLoading(false)}},[allowed,contentId,workspace,zh]);useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh])
 if(!allowed)return <Card className="mx-auto mt-12 max-w-xl text-center"><FileText className="mx-auto size-8 text-coral"/><h2 className="mt-4 text-2xl font-bold">{zh?'需要内部制作权限':'Internal production access required'}</h2></Card>
 if(loading)return <div className="grid min-h-[60vh] place-items-center"><LoaderCircle className="size-8 animate-spin text-coral"/></div>
 if(!workspace||!detail||!workflow||!review||!publishing||!session)return <Card className="mx-auto max-w-xl text-center"><p>{error}</p><Button className="mt-4" onClick={()=>navigate('/content')}>{zh?'返回制作中心':'Back to Production Center'}</Button></Card>
 const{content,sourceIdea,sourceReferences}=detail;const category=catalog.categories.find(c=>c.id===content.category_id);const contributor=(code:string)=>workflow.contributors.find(c=>c.status==='active'&&c.contribution_role_code===code)?.display_name??'—';const latestEvent=workflow.events[0];const latestActivity=workflow.activity[0];const tabText:Record<Tab,string>=zh?{brief:'拍摄简报',script:'脚本',production:'制作',review:'审核与修改',publishing:'发布与数据',activity:'时间线 / Activity'}:{brief:'Shooting Brief',script:'Script',production:'Production',review:'Review & Revisions',publishing:'Publications & Analytics',activity:'Timeline / Activity'}
 return <div className="page-enter space-y-4"><Link to="/content" className="inline-flex items-center gap-2 text-sm font-bold text-ink-muted hover:text-coral"><ArrowLeft className="size-4"/>{zh?'返回制作中心':'Back to Production Center'}</Link>
 <header className="sticky top-0 z-20 rounded-xl border border-line bg-paper/95 px-5 py-4 shadow-sm backdrop-blur"><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-bold text-coral">{content.content_code}</span><StatusBadge tone="info">{enumLabel(content.current_status,language)}</StatusBadge><span className="text-xs font-bold text-ink-muted">{content.ownership_name}</span></div><h1 className="mt-2 truncate text-2xl font-bold sm:text-3xl">{content.title}</h1><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-ink-muted"><span>{zh?'计划日期':'Planned'}: <b className="text-ink">{formatWorkspaceDate(content.planned_date,language)}</b></span><span>{zh?'负责人':'Owner'}: <b className="text-ink">{content.current_owner_name??'—'}</b></span><span>{zh?'出镜':'Talent'}: <b className="text-ink">{sourceIdea?'—':'—'}</b></span></div></div><div className="flex flex-wrap items-center gap-2"><Button variant="secondary" onClick={()=>setBoss(true)}><Video className="size-4"/>{zh?'老板模式 / 拍摄模式':'Boss / Shooting Mode'}</Button>{canManage?<Button variant="secondary" onClick={()=>setEditing(true)}><Pencil className="size-4"/>{zh?'编辑资料':'Edit metadata'}</Button>:null}<Button onClick={()=>setTab('production')}><Clapperboard className="size-4"/>{zh?'执行下一步':'Primary Action'}</Button></div></div></header>
 {error?<div role="alert" className="rounded-lg bg-coral/8 p-3 text-sm text-coral-dark">{error}</div>:null}
 <nav className="flex gap-1 overflow-x-auto rounded-lg border border-line bg-paper p-1">{tabs.map(value=><button key={value} onClick={()=>setTab(value)} className={`shrink-0 rounded-md px-3 py-2 text-sm font-bold ${tab===value?'bg-ink text-white':'text-ink-muted hover:bg-canvas-raised'}`}>{tabText[value]}</button>)}</nav>
 {tab==='brief'?<div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><Card className="min-w-0">{sourceIdea?<ShootingBrief idea={sourceIdea} references={sourceReferences}/>:<div className="py-12 text-center text-ink-muted">{zh?'直接建立的内容没有来源选题拍摄简报。':'Direct-created Content has no source Idea Shooting Brief.'}</div>}</Card><aside className="space-y-4 xl:sticky xl:top-48 xl:self-start"><Card><p className="text-xs font-extrabold uppercase tracking-[.18em] text-coral">{zh?'执行资料':'Execution details'}</p><dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-1">{[[zh?'品牌':'Brand',content.ownership_name],[zh?'分类':'Category',category?.name??'—'],[zh?'负责人':'Owner',content.current_owner_name??'—'],[zh?'出镜人':'Talent','—'],[zh?'拍摄负责人':'Shooter',contributor('shooter')],[zh?'剪辑负责人':'Editor',contributor('editor')],[zh?'审核人':'Reviewer',contributor('reviewer')],[zh?'发布负责人':'Publisher',contributor('publisher')],[zh?'拍摄日期':'Shoot Date',formatWorkspaceDate(workflow.production.shoot_scheduled_at,language)],[zh?'拍摄地点':'Location','—']].map(([k,v])=><div key={k}><dt className="text-xs text-ink-muted">{k}</dt><dd className="mt-1 text-sm font-bold">{v}</dd></div>)}</dl></Card><Card><p className="text-xs font-extrabold uppercase tracking-wider text-ink-faint">{zh?'最近活动':'Recent activity'}</p><p className="mt-3 text-sm font-bold">{latestEvent?enumLabel(latestEvent.event_type,language):latestActivity?.action??(zh?'暂无记录':'No activity')}</p><p className="mt-1 text-xs text-ink-muted">{latestEvent?formatWorkspaceDate(latestEvent.occurred_at,language):latestActivity?formatWorkspaceDate(latestActivity.occurred_at,language):'—'}</p></Card></aside></div>:null}
 {tab==='script'?<ScriptWorkspace contentId={content.id} scripts={review.scripts} canManage={Boolean(canManage)} onChanged={refresh}/>:null}{tab==='production'?<ProductionWorkspace key={`${content.id}-${content.updated_at}`} workspaceId={workspace.id} content={content} bundle={workflow} currentUserId={session.user.id} workspaceRoles={workspace.roles} canManage={Boolean(canManage)} onChanged={refresh}/>:null}{tab==='review'?<ReviewWorkspace content={content} bundle={review} contributors={workflow.contributors} currentUserId={session.user.id} workspaceRoles={workspace.roles} canManage={Boolean(canManage)} onChanged={refresh}/>:null}{tab==='publishing'?<PublishingWorkspace content={content} bundle={publishing} contributors={workflow.contributors} currentUserId={session.user.id} workspaceRoles={workspace.roles} canManage={Boolean(canManage)} onChanged={refresh}/>:null}{tab==='activity'?<TimelineWorkspace bundle={workflow}/>:null}
 {editing&&workspace&&canManage?<ContentFormDrawer workspaceId={workspace.id} catalog={catalog} content={content} canManagePrivateNotes={isSuper||isManager} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await refresh()}}/>:null}{boss&&sourceIdea?<BossMode idea={sourceIdea} onClose={()=>setBoss(false)}/>:null}</div>
}