import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowRight, Columns3, FileText, LayoutList, LoaderCircle, Plus, Search } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Button, Card, Input, Select } from '../components/ui'
import { useAuth } from '../features/auth/auth-context'
import { CampaignManagerDrawer } from '../features/content/CampaignManagerDrawer'
import { ContentFormDrawer } from '../features/content/ContentFormDrawer'
import { loadContentCatalog, loadContents } from '../features/content/content-api'
import { productionBoardStage, productionBoardStages } from '../features/content/production-model'
import type { ContentCatalog, ContentRecord } from '../features/content/content-api'
import { enumLabel, formatWorkspaceDate } from '../features/i18n/labels'
import { useI18n } from '../features/i18n/i18n'
import { useDevMountCounter } from '../lib/dev-diagnostics'

const emptyCatalog: ContentCatalog = { clients: [], categories: [], campaigns: [] }
const stages = productionBoardStages
function phaseLabels(content: ContentRecord, language:'zh-CN'|'en') {
  const s=content.current_status
  return {
    shooting: enumLabel(['draft','ready_to_shoot'].includes(s)?s:['shooting'].includes(s)?'shooting':'shot_awaiting_edit',language),
    editing: enumLabel(['editing','first_cut_submitted'].includes(s)?s:['draft','ready_to_shoot','shooting','shot_awaiting_edit'].includes(s)?'not_started':'completed',language),
    review: enumLabel(['first_cut_submitted','internal_review','revision_required','client_review','approved'].includes(s)?s:['draft','ready_to_shoot','shooting','shot_awaiting_edit','editing'].includes(s)?'not_started':'completed',language),
    publishing: enumLabel(content.publication_state,language),
  }
}

export function ContentPage() {
  useDevMountCounter('ContentPage')
  const { workspace }=useAuth();const navigate=useNavigate();const[params]=useSearchParams();const{language}=useI18n();const zh=language==='zh-CN'
  const[catalog,setCatalog]=useState<ContentCatalog>(emptyCatalog);const[contents,setContents]=useState<ContentRecord[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
  const[search,setSearch]=useState('');const[status,setStatus]=useState(params.get('status')??'all');const[view,setView]=useState<'board'|'table'>('board');const[editing,setEditing]=useState(false);const[managingCampaigns,setManagingCampaigns]=useState(false)
  const isSuperAdmin=workspace?.roles.includes('Super Admin')??false;const isManager=workspace?.roles.includes('Internal Manager')??false;const canManage=isSuperAdmin||isManager||workspace?.roles.includes('Strategist / Content Planner');const allowed=workspace?.roles.some((role)=>!['Client Admin','Client Viewer'].includes(role))??false
  const refresh=useCallback(async()=>{if(!workspace||!allowed)return;setLoading(true);setError(null);try{const[c,r]=await Promise.all([loadContentCatalog(workspace.id),loadContents(workspace.id)]);setCatalog(c);setContents(r)}catch(e){setError(e instanceof Error?e.message:'Could not load production')}finally{setLoading(false)}},[allowed,workspace])
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh])
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return contents.filter((c)=>c.record_status==='active'&&(status==='all'||productionBoardStage(c)===status)&&(!term||[c.content_code,c.title,c.working_title??'',...c.tags].some(v=>v.toLowerCase().includes(term))))},[contents,search,status])
  if(!allowed)return <Card className="mx-auto mt-12 max-w-2xl text-center"><FileText className="mx-auto size-9 text-coral"/><h2 className="mt-4 text-2xl font-bold">{zh?'需要内部制作权限':'Internal production access required'}</h2></Card>
  return <div className="page-enter space-y-5"><header className="flex flex-col gap-4 border-b border-line pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-coral">{zh?'正式制作执行':'Production execution'}</p><h2 className="mt-1 font-display text-3xl font-semibold sm:text-4xl">{zh?'制作中心':'Production Center'}</h2><p className="mt-1 text-sm text-ink-muted">{zh?'已确认内容现在做到哪里，一眼看清。':'See exactly where every confirmed Content is now.'}</p></div>{canManage?<div className="flex gap-2"><Button variant="secondary" onClick={()=>setManagingCampaigns(true)}>{zh?'Campaign 管理':'Campaigns'}</Button><Button onClick={()=>setEditing(true)}><Plus className="size-4"/>{zh?'新增制作内容':'Create Content'}</Button></div>:null}</header>
  {error?<div role="alert" className="rounded-lg border border-coral/30 bg-coral/8 p-3 text-sm text-coral-dark">{error}</div>:null}
  <div className="flex flex-col gap-3 rounded-xl border border-line bg-paper p-3 lg:flex-row lg:items-center"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3 size-4 text-ink-faint"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder={zh?'搜索主题、编号或标签':'Search topic, code, or tag'}/></label><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{zh?'所有制作状态':'All production states'}</option>{stages.map(s=><option key={s} value={s}>{enumLabel(s,language)}</option>)}</Select><div className="flex rounded-lg border border-line p-1"><Button size="sm" variant={view==='board'?'primary':'ghost'} onClick={()=>setView('board')}><Columns3 className="size-4"/>{zh?'看板':'Board'}</Button><Button size="sm" variant={view==='table'?'primary':'ghost'} onClick={()=>setView('table')}><LayoutList className="size-4"/>{zh?'列表':'Table'}</Button></div></div>
  {loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="size-7 animate-spin text-coral"/></div>:view==='board'?<div data-testid="production-board" className="flex gap-3 overflow-x-auto pb-3">{stages.map(stage=>{const rows=filtered.filter(c=>productionBoardStage(c)===stage);return <section key={stage} className="w-72 shrink-0 rounded-xl border border-line bg-canvas-raised/65"><header className="sticky top-0 flex items-center justify-between border-b border-line bg-canvas-raised px-3 py-3"><h3 className="text-xs font-extrabold">{enumLabel(stage,language)}</h3><span className="rounded-full bg-paper px-2 py-0.5 text-xs font-bold">{rows.length}</span></header><div className="space-y-2 p-2">{rows.map(c=><button key={c.id} onClick={()=>navigate(`/content/${c.id}`)} className="w-full rounded-lg border border-line bg-paper p-3 text-left shadow-sm transition hover:-translate-y-px hover:border-coral/45 hover:shadow"><p className="font-mono text-[.65rem] font-bold text-coral">{c.content_code} · {c.ownership_name}</p><h4 className="mt-1.5 line-clamp-3 text-sm font-bold leading-5">{c.title}</h4><div className="mt-3 flex items-center justify-between gap-2 text-xs text-ink-muted"><span>{formatWorkspaceDate(c.planned_date,language,{year:undefined})}</span><span className="truncate">{c.current_owner_name??(zh?'未分配':'Unassigned')}</span></div></button>)}{!rows.length?<p className="py-8 text-center text-xs text-ink-faint">{zh?'暂无内容':'No Content'}</p>:null}</div></section>})}</div>:<Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table data-testid="production-table" className="w-full min-w-[70rem] text-left text-sm"><thead className="sticky top-0 bg-canvas-raised text-[.68rem] font-extrabold uppercase tracking-wider text-ink-faint"><tr><th className="px-4 py-3">{zh?'主题':'Topic'}</th><th className="px-4 py-3">{zh?'拍摄':'Shooting'}</th><th className="px-4 py-3">{zh?'剪辑':'Editing'}</th><th className="px-4 py-3">{zh?'审核':'Review'}</th><th className="px-4 py-3">{zh?'发布':'Publishing'}</th><th className="px-4 py-3">{zh?'负责人':'Owner'}</th></tr></thead><tbody className="divide-y divide-line">{filtered.map(c=>{const phases=phaseLabels(c,language);return <tr key={c.id} onClick={()=>navigate(`/content/${c.id}`)} className="cursor-pointer hover:bg-canvas-raised"><td className="px-4 py-3"><p className="font-bold">{c.title}</p><p className="mt-1 text-xs text-ink-muted">{c.content_code} · {c.ownership_name}</p></td><td className="px-4 py-3">{phases.shooting}</td><td className="px-4 py-3">{phases.editing}</td><td className="px-4 py-3">{phases.review}</td><td className="px-4 py-3">{phases.publishing}</td><td className="px-4 py-3">{c.current_owner_name??'—'}<ArrowRight className="ml-2 inline size-4 text-ink-faint"/></td></tr>})}</tbody></table></div></Card>}
  {editing&&workspace&&canManage?<ContentFormDrawer workspaceId={workspace.id} catalog={catalog} canManagePrivateNotes={isSuperAdmin||isManager} onClose={()=>setEditing(false)} onSaved={async id=>{setEditing(false);await refresh();navigate(`/content/${id}`)}}/>:null}{managingCampaigns&&workspace&&canManage?<CampaignManagerDrawer workspaceId={workspace.id} catalog={catalog} onClose={()=>setManagingCampaigns(false)} onChanged={refresh}/>:null}</div>
}