import{useCallback,useEffect,useMemo,useState}from'react'
import{AlertTriangle,ArrowRight,CheckCircle2,LoaderCircle,Plus,Video}from'lucide-react'
import{useNavigate}from'react-router-dom'
import{Button,Card,StatusBadge}from'../components/ui'
import{useAuth}from'../features/auth/auth-context'
import{loadContents}from'../features/content/content-api'
import{deriveDashboard,derivePublicationAttention,loadCalendarEvents}from'../features/pilot/pilot-api'
import{loadAnalyticsQueue}from'../features/publishing/publishing-api'
import type{CalendarEvent}from'../features/pilot/pilot-api'
import{useI18n}from'../features/i18n/i18n'
const localDate=(date=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)
export function DashboardPage(){const{workspace}=useAuth();const{t}=useI18n();const navigate=useNavigate();const[events,setEvents]=useState<CalendarEvent[]>([]);const[contents,setContents]=useState<Array<{id:string;title:string;client_id:string;current_status:string}>>([]);const[loading,setLoading]=useState(true);const[publicationAttention,setPublicationAttention]=useState<Array<{contentId:string;type:string;title:string}>>([])
const refresh=useCallback(async()=>{if(!workspace)return;setLoading(true);const from=localDate();const future=new Date();future.setDate(future.getDate()+7);const[e,c,q]=await Promise.all([loadCalendarEvents(workspace.id,from,localDate(future)),loadContents(workspace.id),loadAnalyticsQueue(workspace.id)]);setEvents(e);setContents(c);setPublicationAttention(derivePublicationAttention(q.publications,q.snapshots).map(item=>({...item,title:q.contents.find(content=>content.id===item.contentId)?.title??'Content'})));setLoading(false)},[workspace]);useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh]);const data=useMemo(()=>deriveDashboard(events,contents),[events,contents]);const open=(item:CalendarEvent)=>navigate(item.entity_type==='idea'?`/ideas?idea=${item.entity_id}`:`/content/${item.entity_id}`)
const queue=(title:string,items:CalendarEvent[],empty:string)=><Card className="p-0"><div className="border-b border-line px-5 py-4"><h3 className="font-display text-2xl font-semibold">{title}</h3></div>{items.length?<div className="divide-y divide-line">{items.slice(0,7).map(item=><button key={item.event_key} onClick={()=>open(item)} className="flex w-full items-center gap-3 px-5 py-3 text-left hover:bg-canvas-raised"><StatusBadge tone={item.event_type==='SHOOT'?'warning':item.event_type==='PUBLISH'?'success':'info'}>{item.event_type}</StatusBadge><span className="min-w-0 flex-1 truncate font-bold">{item.title}</span><span className="text-xs text-ink-muted">{item.client_name}</span><ArrowRight className="size-4 text-ink-faint"/></button>)}</div>:<div className="p-6 text-sm leading-6 text-ink-muted"><CheckCircle2 className="mb-3 size-6 text-green"/>{empty}</div>}</Card>
return <div className="page-enter space-y-6"><header className="flex flex-col gap-4 border-b border-line pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-coral">{t('today')} / {t('thisWeek')}</p><h2 className="mt-2 font-display text-4xl font-semibold sm:text-5xl">今天要推进什么？</h2><p className="mt-2 text-ink-muted">排期、制作与需要决定的事项集中在这里。</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>navigate('/ideas')}><Plus className="size-4"/>{t('newIdea')}</Button><Button onClick={()=>navigate('/content')}><Plus className="size-4"/>{t('newContent')}</Button></div></header>{loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="size-7 animate-spin text-coral"/></div>:<><div className="grid gap-5 xl:grid-cols-2">{queue('今日计划 / Today',data.todayItems,'今天暂时没有排期。可以先到内容计划安排日期。')}{queue('本周安排 / This Week',data.weekItems,'本周没有计划、拍摄或发布事项。')}</div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card><div className="flex items-center gap-2"><AlertTriangle className="size-5 text-gold-dark"/><h3 className="font-display text-2xl font-semibold">{t('needsAttention')}</h3></div>{data.attention.length||publicationAttention.length?<div className="mt-4 divide-y divide-line">{data.attention.map(item=><button key={item.id} onClick={()=>navigate(`/content/${item.id}`)} className="flex w-full justify-between py-3 text-left"><span className="font-bold">{item.title}</span><StatusBadge tone="warning">{t(item.current_status as never)}</StatusBadge></button>)}{publicationAttention.map((item,index)=><button key={item.contentId+item.type+index} onClick={()=>navigate('/content/'+item.contentId)} className="flex w-full justify-between py-3 text-left"><span className="font-bold">{item.title}</span><StatusBadge tone="critical">{item.type}</StatusBadge></button>)}</div>:<p className="mt-4 text-sm text-ink-muted">目前没有等待审核或修改的内容。发布失败与逾期数据也会出现在这里。</p>}</Card><Card tone="dark"><Video className="size-5 text-coral-light"/><h3 className="mt-3 font-display text-2xl font-semibold">{t('productionOverview')}</h3><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(data.overview).map(([status,count])=><div key={status} className="rounded-lg bg-white/7 p-3"><p className="text-2xl font-bold">{count}</p><p className="mt-1 text-xs text-white/55">{t(status as never)}</p></div>)}</div>{!Object.keys(data.overview).length?<p className="mt-4 text-sm text-white/55">建立第一条 Content 后，制作状态会在这里汇总。</p>:null}</Card></div></>}</div>}
