import { useCallback, useEffect, useState } from 'react'
import { Bell, CheckCheck, LoaderCircle, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button, StatusBadge } from '../../components/ui'
import { loadNotifications, markAllNotificationsRead, markNotificationRead } from './notification-api'
import type { NotificationRecord } from './notification-api'
import { useI18n } from '../i18n/i18n'

export function NotificationBell(){
 const{language}=useI18n();const zh=language==='zh-CN';const navigate=useNavigate();const[open,setOpen]=useState(false);const[items,setItems]=useState<NotificationRecord[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('')
 const refresh=useCallback(async()=>{setLoading(true);try{setItems(await loadNotifications());setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load notifications')}finally{setLoading(false)}},[])
 useEffect(()=>{const initial=window.setTimeout(()=>void refresh(),0);const timer=window.setInterval(()=>void refresh(),60000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[refresh])
 const unread=items.filter(item=>!item.read_at).length
 async function openItem(item:NotificationRecord){if(!item.read_at)await markNotificationRead(item.id);setOpen(false);navigate(item.route);void refresh()}
 return <><button type="button" onClick={()=>{setOpen(true);void refresh()}} className="relative grid size-10 place-items-center rounded-lg border border-line bg-white text-ink-muted hover:border-blue/40 hover:text-blue" aria-label={zh?'通知':'Notifications'}><Bell className="size-4"/>{unread?<span className="absolute -right-1.5 -top-1.5 min-w-5 rounded-full bg-coral px-1 text-center text-[10px] font-extrabold leading-5 text-white">{unread>99?'99+':unread}</span>:null}</button>{open?<div className="fixed inset-0 z-50 flex justify-end bg-ink/35" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="flex h-full w-full max-w-md flex-col bg-paper shadow-2xl"><header className="flex items-center justify-between border-b border-line px-5 py-4"><div className="flex items-center gap-2"><h2 className="text-xl font-bold">{zh?'通知中心':'Notifications'}</h2>{unread?<StatusBadge tone="info">{unread} {zh?'未读':'unread'}</StatusBadge>:null}</div><Button size="icon" variant="ghost" onClick={()=>setOpen(false)}><X className="size-5"/></Button></header><div className="flex items-center justify-between border-b border-line px-5 py-3"><p className="text-xs text-ink-muted">{zh?'只发送给相关负责人':'Only relevant owners and assignees are notified'}</p><Button size="sm" variant="ghost" disabled={!unread} onClick={async()=>{await markAllNotificationsRead();await refresh()}}><CheckCheck className="size-4"/>{zh?'全部已读':'Mark all read'}</Button></div><div className="flex-1 overflow-y-auto">{loading&&!items.length?<div className="grid h-48 place-items-center"><LoaderCircle className="size-6 animate-spin text-coral"/></div>:items.map(item=><button key={item.id} onClick={()=>void openItem(item)} className={`block w-full border-b border-line px-5 py-4 text-left hover:bg-canvas-raised ${item.read_at?'opacity-65':'bg-blue/5'}`}><div className="flex items-start gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${item.read_at?'bg-line-strong':'bg-coral'}`}/><div className="min-w-0 flex-1"><p className="font-bold">{item.title}</p>{item.body?<p className="mt-1 line-clamp-2 text-sm leading-5 text-ink-muted">{item.body}</p>:null}<time className="mt-2 block text-xs text-ink-faint">{new Date(item.created_at).toLocaleString(zh?'zh-CN':'en-MY')}</time></div></div></button>)}{!loading&&!items.length?<div className="p-10 text-center"><Bell className="mx-auto size-7 text-ink-faint"/><p className="mt-3 font-bold">{zh?'没有新通知':'No notifications'}</p></div>:null}{error?<p className="m-4 rounded-lg bg-coral/8 p-3 text-sm text-coral-dark">{error}</p>:null}</div></section></div>:null}</>
}
