import { supabase } from '../../lib/supabase'

export type EditingPresetCategory='subtitle'|'brand_logo'|'pacing'|'transition'|'bgm_sfx'|'cover'|'export'|'gold_standard'|'custom'
export interface EditingPreset {id:string;workspace_id:string;client_id:string;name:string;category:EditingPresetCategory;preset_type:'style'|'sop';purpose:string|null;settings:Record<string,unknown>;steps:Array<Record<string,unknown>>;example_links:string[];notes:string|null;version_number:number;sort_order:number;is_default:boolean;status:'active'|'inactive';updated_by:string;updated_by_name?:string;updated_at:string}
export interface ContentPresetSnapshot{id:string;content_id:string;preset_id:string;usage_slot:'subtitle'|'opening'|'info_insert'|'other';preset_version:number;preset_snapshot:Record<string,unknown>;assigned_at:string}
export interface EditingPresetInput{id?:string;clientId:string;name:string;category:EditingPresetCategory;presetType:'style'|'sop';purpose:string;settings:Record<string,unknown>;steps:Array<Record<string,unknown>>;exampleLinks:string[];notes:string;sortOrder:number;isDefault:boolean;status:'active'|'inactive'}

function fail(error:{message:string}|null){if(error)throw new Error(error.message)}
export async function loadEditingPresets(clientId:string){const{data,error}=await supabase.from('editing_presets').select('*,updated_by_profile:user_profiles!editing_presets_updated_by_fkey(display_name)').eq('client_id',clientId).order('sort_order').order('name');fail(error);return(data??[]).map(row=>{const value=row as EditingPreset&{updated_by_profile?:{display_name?:string}|null};return{...value,updated_by_name:value.updated_by_profile?.display_name}})}
export async function loadContentPresetSnapshots(contentId:string){const{data,error}=await supabase.from('content_editing_presets').select('*').eq('content_id',contentId).order('assigned_at',{ascending:false});fail(error);return(data??[]) as ContentPresetSnapshot[]}
export async function saveEditingPreset(value:EditingPresetInput){const{data,error}=await supabase.rpc('save_editing_preset',{target_preset_id:value.id??null,target_client_id:value.clientId,target_name:value.name,target_category:value.category,target_preset_type:value.presetType,target_purpose:value.purpose,target_settings:value.settings,target_steps:value.steps,target_example_links:value.exampleLinks,target_notes:value.notes,target_sort_order:value.sortOrder,target_is_default:value.isDefault,target_status:value.status});fail(error);return data as string}
export async function copyEditingPreset(id:string,name:string){const{data,error}=await supabase.rpc('copy_editing_preset',{target_preset_id:id,target_name:name});fail(error);return data as string}
export async function deleteUnusedEditingPreset(id:string){const{error}=await supabase.rpc('delete_unused_editing_preset',{target_preset_id:id});fail(error)}
export async function assignContentEditingPreset(contentId:string,presetId:string,slot:'subtitle'|'opening'|'info_insert'|'other'){const{data,error}=await supabase.rpc('assign_content_editing_preset',{target_content_id:contentId,target_preset_id:presetId,target_usage_slot:slot});fail(error);return data as string}
