import{useState}from'react'
import{NavLink}from'react-router-dom'
import{ChevronDown,X}from'lucide-react'
import{routeDefinitions}from'../lib/navigation'
import{cn}from'../lib/cn'
import{useAuth}from'../features/auth/auth-context'
import{routeTranslationKeys,useI18n}from'../features/i18n/i18n'
import type{TranslationKey}from'../features/i18n/i18n'
import{isIdeaContributorOnly}from'../features/auth/role-access'
interface SidebarProps{mobileOpen:boolean;onClose:()=>void}
const sections=[['Daily Work','dailyWork'],['Brand','brand'],['Results','results'],['Management','management'],['Resources','resources'],['Settings',null]] as const
function NavigationContent({onNavigate}:{onNavigate?:()=>void}){const{workspace}=useAuth();const{t}=useI18n();const[resourcesOpen,setResourcesOpen]=useState(false);const admin=workspace?.roles.includes('Super Admin')??false;const contributor=workspace?.roles.includes('Idea Contributor')??false;const contributorOnly=isIdeaContributorOnly(workspace?.roles??[]);const research=admin||workspace?.roles.includes('Internal Manager')||workspace?.roles.includes('Strategist / Content Planner')||contributor;const internal=workspace?.roles.some(role=>!['Client Admin','Client Viewer','Idea Contributor'].includes(role))??false;return <><div className="border-b border-white/10 px-5 py-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-lg bg-primary font-display text-xl font-bold text-white">C</div><div><p className="font-display text-xl font-semibold text-white">ContentOS</p><p className="text-[.65rem] font-bold uppercase tracking-[.2em] text-white/45">Daily operations</p></div></div></div><nav className="flex-1 overflow-y-auto px-3 py-4">{sections.map(([section,key])=>{const routes=routeDefinitions.filter(route=>(!contributorOnly||route.path==='/ideas')&&route.section===section&&!['/references','/assets','/music','/editing-playbook'].includes(route.path)&&(route.path!=='/team'||admin)&&(!['/ideas','/references'].includes(route.path)||research)&&(route.path!=='/content'||internal)&&(!['/tasks','/equipment-proposals'].includes(route.path)||internal));if(!routes.length)return null;if(section==='Resources')return <div key={section} className="mb-4"><button type="button" onClick={()=>setResourcesOpen(!resourcesOpen)} className="flex w-full items-center justify-between px-3 py-2 text-[.65rem] font-extrabold uppercase tracking-[.2em] text-white/45"><span>{t('resources')}</span><ChevronDown className={cn('size-4 transition',resourcesOpen&&'rotate-180')}/></button>{resourcesOpen?<div className="space-y-1">{routes.map(route=><Nav route={route} key={route.path} t={t} onNavigate={onNavigate}/>)}</div>:null}</div>;return <div key={section} className="mb-4">{key?<p className="mb-2 px-3 text-[.62rem] font-extrabold uppercase tracking-[.22em] text-white/35">{t(key)}</p>:null}<div className="space-y-1">{routes.map(route=><Nav route={route} key={route.path} t={t} onNavigate={onNavigate}/>)}</div></div>})}</nav></>}
function Nav({route,t,onNavigate}:{route:(typeof routeDefinitions)[number];t:(key:TranslationKey)=>string;onNavigate?:()=>void}){const Icon=route.icon;return <NavLink to={route.path} end={route.path==='/'} onClick={onNavigate} className={({isActive})=>cn('group flex min-h-11 items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold transition',isActive?'bg-primary text-white':'text-white/70 hover:bg-nav-hover hover:text-white')}><Icon className="size-[1.05rem]"/><span>{t(routeTranslationKeys[route.path])}</span></NavLink>}
export function Sidebar({mobileOpen,onClose}:SidebarProps){return <><aside className="fixed inset-y-0 left-0 z-30 hidden w-sidebar flex-col bg-nav lg:flex"><NavigationContent/></aside><div className={cn('fixed inset-0 z-40 bg-nav/60 transition lg:hidden',mobileOpen?'opacity-100':'pointer-events-none opacity-0')} onClick={onClose}/><aside className={cn('fixed inset-y-0 left-0 z-50 flex w-[min(86vw,20rem)] flex-col bg-nav shadow-2xl transition-transform lg:hidden',mobileOpen?'translate-x-0':'-translate-x-full')}><button className="absolute right-3 top-3 grid size-10 place-items-center text-white" onClick={onClose}><X className="size-5"/></button><NavigationContent onNavigate={onClose}/></aside></>}
