import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { AlertTriangle, BarChart3, CalendarClock, CheckCircle2, ExternalLink, Plus, Send } from 'lucide-react'
import { Button, Card, Input, Select, StatusBadge } from '../../components/ui'
import type { ContentRecord } from '../content/content-api'
import type { ContentContributorRecord } from '../content/workflow-api'
import { addManualSnapshot, cancelPublication, completeContentAnalytics, createPublication, markPublicationFailed, markPublicationPublished, saveSocialAccount, schedulePublication } from './publishing-api'
import type { AnalyticsSnapshotRecord, MetricInput, PublicationRecord, PublishingBundle, SnapshotType } from './publishing-api'
import { useI18n } from '../i18n/i18n'
import { enumLabel } from '../i18n/labels'

interface Props { content:ContentRecord; bundle:PublishingBundle; contributors:ContentContributorRecord[]; currentUserId:string; workspaceRoles:string[]; canManage:boolean; onChanged:()=>Promise<void> }
const label=(v:string)=>v.split('_').map((p)=>p[0]?.toUpperCase()+p.slice(1)).join(' ')
const format=(v:string|null)=>v?new Date(v).toLocaleString('en-MY'):'—'
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const emptyMetrics:MetricInput={viewsOrPlays:'',reach:'',impressions:'',likes:'',comments:'',shares:'',savesOrCollects:'',clicks:'',followersGained:''}
const stateTone=(state:string)=>state==='fully_published'?'success':state==='needs_attention'?'critical':state==='partially_published'?'warning':'neutral'

export function PublishingWorkspace({content,bundle,contributors,currentUserId,workspaceRoles,canManage,onChanged}:Props){
  const {language}=useI18n();const zh=language==='zh-CN'
  const [busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null)
  const[account,setAccount]=useState({platformId:bundle.platforms[0]?.id??'',name:'',handle:'',url:''})
  const[plan,setPlan]=useState({platformId:bundle.platforms[0]?.id??'',accountId:'',publisherId:'',required:true,note:''})
  const publishers=contributors.filter((c)=>c.status==='active'&&c.contribution_role_code==='publisher')
  const accounts=bundle.accounts.filter((a)=>a.client_id===content.client_id)
  const assignedPublisher=workspaceRoles.includes('Publisher / Marketing')
  async function run(key:string,action:()=>Promise<unknown>){setBusy(key);setError(null);try{await action();await onChanged()}catch(c){setError(c instanceof Error?c.message:'Publishing action failed')}finally{setBusy(null)}}
  async function addAccount(e:FormEvent){e.preventDefault();await run('account',()=>saveSocialAccount({clientId:content.client_id,platformId:account.platformId,name:account.name,handle:account.handle,url:account.url}))}
  async function addPublication(e:FormEvent){e.preventDefault();await run('publication',()=>createPublication({contentId:content.id,platformId:plan.platformId,accountId:plan.accountId,publisherId:plan.publisherId,required:plan.required,note:plan.note}))}
  const snapshotsByPublication=useMemo(()=>new Map(bundle.publications.map((p)=>[p.id,bundle.snapshots.filter((s)=>s.publication_id===p.id)])),[bundle])
  return <div className="space-y-6">
    {error?<div className="rounded-md border border-coral/30 bg-coral/8 p-3 text-sm text-coral-dark">{error}</div>:null}
    <Card className="overflow-hidden p-0"><div className="grid lg:grid-cols-[1fr_18rem]"><section className="p-5 sm:p-6"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-coral">{zh?'发布控制':'Publication control'}</p><h3 className="mt-3 font-display text-3xl font-semibold">{zh?'各平台独立发布，记录统一追踪。':'Independent channels, one accountable record.'}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-muted">Facebook and Xiaohongshu remain separate Publications. Their actual times, links, failures, and snapshots never overwrite each other.</p></section><aside className="border-t border-line bg-canvas-raised p-5 lg:border-l lg:border-t-0"><p className="text-xs font-bold uppercase tracking-wider text-ink-faint">{zh?'整体发布状态':'Aggregate state'}</p><StatusBadge className="mt-3" tone={stateTone(bundle.aggregate)}>{enumLabel(bundle.aggregate,language)}</StatusBadge><p className="mt-3 text-xs leading-5 text-ink-muted">Derived from required Publication records; there is no published checkbox.</p></aside></div></Card>

    {canManage?<div className="grid gap-6 xl:grid-cols-2"><Card><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">{zh?'社交账号资料':'Social account metadata'}</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={addAccount}><Select value={account.platformId} onChange={(e)=>setAccount({...account,platformId:e.target.value})}>{bundle.platforms.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Input required placeholder={zh?'账号名称':'Account name'} value={account.name} onChange={(e)=>setAccount({...account,name:e.target.value})}/><Input required placeholder="@handle / page identifier" value={account.handle} onChange={(e)=>setAccount({...account,handle:e.target.value})}/><Input placeholder={zh?'公开账号链接':'Public account URL'} value={account.url} onChange={(e)=>setAccount({...account,url:e.target.value})}/><Button className="sm:col-span-2 sm:justify-self-start" disabled={busy!==null}><Plus className="size-4"/>{zh?'新增账号':'Add account'}</Button></form><p className="mt-3 text-xs text-ink-muted">Metadata only. No OAuth token, password, cookie, or API credential is stored.</p></Card>
    <Card><p className="text-xs font-extrabold uppercase tracking-[.18em] text-ink-faint">{zh?'新增发布记录':'Add publication'}</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={addPublication}><Select value={plan.platformId} onChange={(e)=>setPlan({...plan,platformId:e.target.value,accountId:''})}>{bundle.platforms.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Select required value={plan.accountId} onChange={(e)=>setPlan({...plan,accountId:e.target.value})}><option value="">{zh?'选择账号':'Select account'}</option>{accounts.filter((a)=>a.platform_id===plan.platformId).map((a)=><option key={a.id} value={a.id}>{a.account_name} · {a.account_handle}</option>)}</Select><Select required value={plan.publisherId} onChange={(e)=>setPlan({...plan,publisherId:e.target.value})}><option value="">{zh?'选择发布负责人':'Assigned Publisher'}</option>{publishers.map((p)=><option key={p.user_profile_id} value={p.user_profile_id}>{p.display_name}</option>)}</Select><Select value={plan.required?'required':'optional'} onChange={(e)=>setPlan({...plan,required:e.target.value==='required'})}><option value="required">{zh?'必须发布':'Required'}</option><option value="optional">{zh?'选填':'Optional'}</option></Select><Input className="sm:col-span-2" placeholder={zh?'发布备注':'Publication note'} value={plan.note} onChange={(e)=>setPlan({...plan,note:e.target.value})}/><Button className="sm:col-span-2 sm:justify-self-start" disabled={busy!==null||!plan.accountId||!plan.publisherId}><Plus className="size-4"/>{zh?'建立发布记录':'Create publication'}</Button></form></Card></div>:null}

    <div className="space-y-5">{bundle.publications.length?bundle.publications.map((publication)=><PublicationCard key={publication.id} publication={publication} account={accounts.find((a)=>a.id===publication.social_account_id)} platform={bundle.platforms.find((p)=>p.id===publication.platform_id)} snapshots={snapshotsByPublication.get(publication.id)??[]} canExecute={assignedPublisher&&publication.assigned_publisher_user_id===currentUserId} canAddAnalytics={canManage||(assignedPublisher&&publication.assigned_publisher_user_id===currentUserId)} busy={busy} run={run}/>):<Card className="border-dashed text-center"><Send className="mx-auto size-7 text-ink-faint"/><p className="mt-3 font-bold">{zh?'还没有发布计划':'No Publication plan yet'}</p><p className="mt-1 text-sm text-ink-muted">Approved Content stays Not Published until independent target records are created.</p></Card>}</div>
    {content.current_status==='analytics_tracking'&&canManage?<Card tone="quiet"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-bold">{zh?'完成数据复盘':'Complete strategy review'}</p><p className="mt-1 text-xs text-ink-muted">Requires Fully Published plus 24h, 7d, and 30d snapshots for every required Publication.</p></div><Button disabled={busy!==null} onClick={()=>{const note=window.prompt('Completion note:')?.trim();if(note)void run('complete',()=>completeContentAnalytics(content.id,content.current_status,note))}}><CheckCircle2 className="size-4"/>{zh?'标记已复盘 / 完成':'Mark Reviewed / Completed'}</Button></div></Card>:null}
  </div>
}

function PublicationCard({publication,account,platform,snapshots,canExecute,canAddAnalytics,busy,run}:{publication:PublicationRecord;account?:{account_name:string;account_handle:string};platform?:{name:string};snapshots:AnalyticsSnapshotRecord[];canExecute:boolean;canAddAnalytics:boolean;busy:string|null;run:(key:string,action:()=>Promise<unknown>)=>Promise<void>}){
  const {language}=useI18n();const zh=language==='zh-CN'
  const[schedule,setSchedule]=useState(localNow());const[publishedAt,setPublishedAt]=useState(localNow());const[url,setUrl]=useState(publication.post_url??'');const[note,setNote]=useState('');const[failure,setFailure]=useState('')
  const[type,setType]=useState<SnapshotType>('24h');const[capturedAt,setCapturedAt]=useState(localNow());const[metrics,setMetrics]=useState<MetricInput>(emptyMetrics);const[snapshotNote,setSnapshotNote]=useState('')
  const latest=snapshots[0]
  return <Card className={publication.status==='failed'?'border-coral/35':''}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-display text-2xl font-semibold">{platform?.name??'Platform'} · {account?.account_name??'Account'}</p><StatusBadge tone={publication.status==='failed'?'critical':publication.status==='published'?'success':publication.status==='scheduled'?'warning':'neutral'}>{enumLabel(publication.status,language)}</StatusBadge><StatusBadge>{publication.is_required?(zh?'必须发布':'Required'):(zh?'选填':'Optional')}</StatusBadge></div><p className="mt-1 text-xs text-ink-muted">{account?.account_handle} · sequence {publication.publication_sequence}</p></div>{publication.post_url?<a href={publication.post_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-bold text-blue hover:underline">{zh?'打开贴文':'Open post'} <ExternalLink className="size-3.5"/></a>:null}</div>
    <dl className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-md border border-line p-3"><dt className="text-[.65rem] font-bold uppercase tracking-wider text-ink-faint">{zh?'计划发布':'Scheduled'}</dt><dd className="mt-1 text-sm font-semibold">{format(publication.scheduled_at)}</dd></div><div className="rounded-md border border-line p-3"><dt className="text-[.65rem] font-bold uppercase tracking-wider text-ink-faint">{zh?'实际发布':'Published'}</dt><dd className="mt-1 text-sm font-semibold">{format(publication.published_at)}</dd></div><div className="rounded-md border border-line p-3"><dt className="text-[.65rem] font-bold uppercase tracking-wider text-ink-faint">{zh?'最新数据':'Latest capture'}</dt><dd className="mt-1 text-sm font-semibold">{latest?`${label(latest.snapshot_type)} · ${format(latest.captured_at)}`:'No snapshot'}</dd></div></dl>
    {publication.failure_reason?<p className="mt-4 flex items-center gap-2 rounded-md bg-coral/8 p-3 text-sm font-semibold text-coral-dark"><AlertTriangle className="size-4"/>{publication.failure_reason}</p>:null}
    {canExecute&&publication.status!=='published'&&publication.status!=='cancelled'?<div className="mt-5 grid gap-3 border-t border-line pt-5 lg:grid-cols-[1fr_1fr_1fr_auto]"><Input type="datetime-local" value={schedule} onChange={(e)=>setSchedule(e.target.value)}/><Input type="datetime-local" value={publishedAt} onChange={(e)=>setPublishedAt(e.target.value)}/><Input placeholder={zh?'发布链接':'Published URL'} value={url} onChange={(e)=>setUrl(e.target.value)}/><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={busy!==null} onClick={()=>void run(`schedule-${publication.id}`,()=>schedulePublication(publication.id,publication.status,new Date(schedule).toISOString(),note))}><CalendarClock className="size-3.5"/>{zh?'排程':'Schedule'}</Button><Button size="sm" disabled={busy!==null||!url} onClick={()=>void run(`publish-${publication.id}`,()=>markPublicationPublished(publication.id,publication.status,new Date(publishedAt).toISOString(),url,note))}>{zh?'标记已发布':'Published'}</Button></div><Input className="lg:col-span-2" placeholder={zh?'动作备注':'Action note'} value={note} onChange={(e)=>setNote(e.target.value)}/><Input placeholder={zh?'失败原因':'Failure reason'} value={failure} onChange={(e)=>setFailure(e.target.value)}/><div className="flex gap-2"><Button size="sm" variant="ghost" disabled={!failure||busy!==null} onClick={()=>void run(`fail-${publication.id}`,()=>markPublicationFailed(publication.id,publication.status,failure,note))}>{zh?'标记失败':'Mark failed'}</Button><Button size="sm" variant="ghost" disabled={busy!==null} onClick={()=>{const reason=window.prompt('Cancellation reason:')?.trim();if(reason)void run(`cancel-${publication.id}`,()=>cancelPublication(publication.id,publication.status,reason))}}>{zh?'取消发布':'Cancel'}</Button></div></div>:null}
    {publication.status==='published'&&canAddAnalytics?<details className="mt-5 border-t border-line pt-5"><summary className="cursor-pointer text-sm font-bold text-blue">{zh?'新增手动数据快照':'Add Manual Analytics Snapshot'}</summary><div className="mt-4 grid gap-3 sm:grid-cols-3"><Select value={type} onChange={(e)=>setType(e.target.value as SnapshotType)}><option value="24h">24h</option><option value="7d">7d</option><option value="30d">30d</option><option value="current">Current</option></Select><Input type="datetime-local" value={capturedAt} onChange={(e)=>setCapturedAt(e.target.value)}/><Input disabled value="Manual" aria-label="Data source"/>{Object.entries({viewsOrPlays:'Views / plays',reach:'Reach',impressions:'Impressions',likes:'Likes',comments:'Comments',shares:'Shares',savesOrCollects:'Saves / collects',clicks:'Clicks',followersGained:'Followers gained'}).map(([key,text])=><Input key={key} type="number" min="0" placeholder={`${text} · blank if N/A`} value={metrics[key as keyof MetricInput]} onChange={(e)=>setMetrics({...metrics,[key]:e.target.value})}/>)}<Input className="sm:col-span-2" placeholder={zh?'数据备注':'Snapshot note'} value={snapshotNote} onChange={(e)=>setSnapshotNote(e.target.value)}/><Button disabled={busy!==null} onClick={()=>void run(`snapshot-${publication.id}`,()=>addManualSnapshot(publication.id,new Date(capturedAt).toISOString(),type,metrics,snapshotNote))}><BarChart3 className="size-4"/>{zh?'保存数据快照':'Save snapshot'}</Button></div></details>:null}
    {snapshots.length?<div className="mt-5 overflow-x-auto border-t border-line pt-5"><table className="w-full min-w-[48rem] text-left text-xs"><thead className="text-ink-faint"><tr><th className="py-2">Window</th><th>Captured</th><th>Views</th><th>Reach</th><th>Likes</th><th>Comments</th><th>Shares</th><th>Saves</th></tr></thead><tbody>{snapshots.map((s)=><tr key={s.id} className="border-t border-line"><td className="py-2 font-bold">{label(s.snapshot_type)}</td><td>{format(s.captured_at)}</td>{[s.views_or_plays,s.reach,s.likes,s.comments,s.shares,s.saves_or_collects].map((v,i)=><td key={i}>{v??'—'}</td>)}</tr>)}</tbody></table></div>:null}
  </Card>
}
